### ISSUE TITLE
Terminal is not updated when View returns empty String

### ISSUE THREAD

**Issue by treilik** [charmbracelet/bubbletea#100]
When a empty string is returned by the View function the prior output is untouched or frozen.
The expected behavior would be a plank screen.

**Comment by meowgorithm** [comment]
Thank for reporting this, @treilik! I've fixed this internally and it will be included in the next release.

**Comment by meowgorithm** [comment]
Thanks again, @treilik. This is now fixed in `master` and will be available in the next release which will come out today.
