### ISSUE TITLE
First line not rendering until event happens

### ISSUE THREAD

**Issue by mistakenelf** [charmbracelet/bubbletea#1000]
**Describe the bug**
Just updated to 0.26.1 and noticed that the first line of my UI does not render until an event takes place(keypress, window resize etc). When downgrading to 0.25, everything works correctly, just wondering if something new was introduced/fixed that I need to account for or if this is maybe a regression?

**Setup**
Please complete the following information along with version numbers, if applicable.
 - OS = macOS
 - Shell = zsh
 - Terminal Emulator = warp
 - Terminal Multiplexer = N/A

**To Reproduce**
1. Go to https://github.com/mistakenelf/fm
2. Run the app by running `make`
3. Noticed that the first line is not rendered until a keypress is made or window is resized
4. Downgrade to 0.25 of bubbletea, and noticed that it works as expected

**Source Code**
 https://github.com/mistakenelf/fm

**Expected behavior**
The first line of the UI should render without any actions

**Screenshots**
 _Notice that the first line of the filetree and the help screen on the right are not rendering until an action happens_

<img width="1050" alt="image" src="https://github.com/charmbracelet/bubbletea/assets/5757096/3e7ef093-096d-42e4-a7b5-4cb15a02c8bc">

**Comment by meowgorithm** [comment]
Noted, thanks for the report, Tyler. I'm able to reproduce on various terminals on macOS. Just so we can diagnose properly, would you mind posting a screenshot of the actual expected outputs together?

**Comment by mistakenelf** [comment]
Sure thing, here is what the expected output would look like:

<img width="1050" alt="default" src="https://github.com/charmbracelet/bubbletea/assets/5757096/9c2e5fbf-c745-421b-a00a-25e1946f10c5">

**Comment by meowgorithm** [comment]
Thanks again for reporting this, @mistakenelf — extremely appreciated. @aymanbagabas fixed this like a pro and we're releasing Bubble Tea v0.26.2 with the fix in a few minutes.
