### ISSUE TITLE
Exiting fullscreen glitch when also removing a line in output

### ISSUE THREAD

**Issue by applejag** [charmbracelet/bubbletea#1013]
**Describe the bug**
When conditionally rendering a line if you're full screen, then when you exit full screen it clears too many lines and removes terminal output that isn't part of 

**Setup**
Please complete the following information along with version numbers, if applicable.
 - OS: Linux, NixOS
 - Shell: tested and getting the same glitch in bash, zsh, fish, and pwsh
 - Terminal Emulator: only tested alacritty, kitty, and iterm
 - Terminal Multiplexer: tested both with and without tmux

**To Reproduce**
1. Have some history in your terminal
2. `go run .`
3. click <kbd>f</kbd> to enter fullscreen and then again to exit fullscreen (doesn't have to be double clicked quickly. The glitch is not time sensitive at all actually)
4. repeat step 3 and see how it clears 1 line at a time from your terminal history

**Source Code**
```go
package main

import (
	"fmt"
	"os"

	tea "github.com/charmbracelet/bubbletea"
)

func main() {
	p := tea.NewProgram(model{})
	if _, err := p.Run(); err != nil {
		fmt.Printf("Alas, there's been an error: %v", err)
		os.Exit(1)
	}
}

type model struct {
	isFullscreen bool
}

func (m model) Init() tea.Cmd {
	return nil
}

func (m model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	switch msg := msg.(type) {
	case tea.KeyMsg:
		switch msg.String() {

		// These keys should exit the program.
		case "ctrl+c", "q":
			return m, tea.Quit

		// Toggle fullscreen
		case "f":
			m.isFullscreen = !m.isFullscreen
			if m.isFullscreen {
				return m, tea.EnterAltScreen
			} else {
				return m, tea.ExitAltScreen
			}
		}
	}
	return m, nil
}

func (m model) View() string {
	s := "Hello\n"

	if m.isFullscreen {
		s += "yay we're fullscreen\n"
	}

	s += "\nPress q to quit.\n"

	return s
}
```

**Expected behavior**
When exiting full screen mode, tea renders the view first before trying to figure out how many lines to clear.

**Screenshots**
When first just running the program:

![image](https://github.com/charmbracelet/bubbletea/assets/2477952/ecbbdd46-4f52-41d9-bd67-e5a097a6315a)

After clicking <kbd>f</kbd> to enter fullscreen:

![image](https://github.com/charmbracelet/bubbletea/assets/2477952/465cb4e4-0993-4d0e-abba-dde5048af022)

Then clicking <kbd>f</kbd> again to exit:

![image](https://github.com/charmbracelet/bubbletea/assets/2477952/7266778f-94e9-401d-ac47-8a14b372247a)

Doing that again, clicking <kbd>f</kbd> twice, results in another line removed:

![image](https://github.com/charmbracelet/bubbletea/assets/2477952/29ffc5c7-16df-4721-9881-49294a390b04)

Double clicking again:

![image](https://github.com/charmbracelet/bubbletea/assets/2477952/e6cdb164-7ddc-4cbc-99ac-7e201caf9c7c)

And again:

![image](https://github.com/charmbracelet/bubbletea/assets/2477952/aea3627b-4dc4-44ed-a6d0-ac0cd8610b47)

**Additional context**
As a more real-life example, in my real program I have all the normal output, but then conditionally a status bar at the end.

When toggling fullscreen it will add a status line to my program saying "forcing fullscreen". Then if there are no other status messages, when I get out of full screen then the status line should also disappear, leading to the bug/glitch explained in this issue.

**Comment by semihbkgr** [comment]
Additionally, reversing the condition leaves more lines in the terminal after toggling the full screen. For example:

eg:
```go
if !m.isFullscreen {
        s += "yay we're fullscreen\n"
}
```

keeps leftover lines in the terminal

**Comment by meowgorithm** [comment]
Hi! This is now fixed on `main` and will be in the next release, which we expect to cut today.

**Comment by meowgorithm** [comment]
Alright, [`v1.2.3`](https://github.com/charmbracelet/bubbletea/releases/tag/v1.2.3), containing the fix, is available now. Thanks again for filing the issue, @applejag, and thanks again @semihbkgr for the fix.
