### ISSUE TITLE
SetWindowTitle panic after upgrade from v0.26.2 ->  v0.26.3

### ISSUE THREAD

**Issue by DziedzicGrzegorz** [charmbracelet/bubbletea#1029]
**Describe the bug**

The application crashes with a runtime error: "invalid memory address or nil pointer dereference" when trying to set the window title using Bubble Tea's `SetWindowTitle` method.

This behavior occurs on both Windows and Ubuntu

**Source Code**
```go
func main() {
    var rootCmd = &cobra.Command{
        Use:   "game",
        Short: "Tic-Tac-Toe game",
        Long:  "A simple Tic-Tac-Toe game written in Go using the Bubble Tea library and the Lip Gloss library.",
        Run: func(cmd *cobra.Command, args []string) {
            p := tea.NewProgram(model{}, tea.WithAltScreen())
            p.SetWindowTitle("Welcome to the game")
            if _, err := p.Run(); err != nil {
                fmt.Fprintf(os.Stderr, "Error: %v\n", err)
                os.Exit(1)
            }
        },
    }

    if err := rootCmd.Execute(); err != nil {
        fmt.Fprintf(os.Stderr, "Error: %v\n", err)
        os.Exit(1)
    }
}
```
![nilPointer](https://github.com/charmbracelet/bubbletea/assets/110931212/906b6d78-ee41-4567-b68c-9f95c1afd838)

**Comment by aymanbagabas** [comment]
Hi @DziedzicGrzegorz, that's a bug indeed! FWIW, using `p.SetWindowTitle` is deprecated or should be, you should use `tea.SetWindowTitle` instead in your model `Init()`. Meanwhile, I will push a fix for this bug momentarily.
