### ISSUE TITLE
Native mouse support in Windows Terminal

### ISSUE THREAD

**Issue by irevenko** [charmbracelet/bubbletea#103]
I've tried [this example](https://github.com/charmbracelet/bubbletea/blob/master/examples/mouse/main.go) on Windows Terminal which is new [replacement](https://github.com/microsoft/terminal) for cmd
nor cmd nor power shell mode are working and most of the time ```(x y)``` bar is not rendering
![ezgif-4-8189ee8a9868](https://user-images.githubusercontent.com/44785096/120027596-6a136900-bfa8-11eb-9859-67212a51687c.gif)

**Comment by meowgorithm** [comment]
If you’re using the [Windows Linux Subsystem](https://docs.microsoft.com/en-us/windows/wsl/about) in Windows Terminal the mouse will work (you can enter the subsystem with `wsl`).

Beyond that, I'm not entirely sure if Windows Terminal supports the mouse outside of WSL so we'll need to do some research here. Currently, we're only processing X10/X11 mouse events (which all unix-like system support).

**Comment by irevenko** [comment]
But you did write support for usual win command line

**Comment by meowgorithm** [comment]
@irevenko If it's possible to add native mouse support in Windows we'll definitely do it. In the meantime, you're welcome to submit a PR which adds the functionality.

**Comment by jon4hz** [comment]
If I remember correctly, [gocui](https://github.com/awesome-gocui/gocui) has implemented mouse support for Linux and for Windows. Maybe you can take a look at how they did it. Unfortunately I can't do a PR as this is beyond my skill level

**Comment by erikgeiser** [comment]
Windows supports mouse events which can be read (alongside all other input events) with [ReadConsoleInput](https://docs.microsoft.com/de-de/windows/console/readconsoleinput). However, this means that the Windows input event parsing logic (which would then be based on [INPUT_RECORD](https://docs.microsoft.com/de-de/windows/console/input-record-str) structs) would have to be decoupled from the Unix logic.

This is quite a bit of work but if the Windows implementation is rewritten to read  [INPUT_RECORD](https://docs.microsoft.com/de-de/windows/console/input-record-str)s, it can also likely use [PeekConsoleInput](https://docs.microsoft.com/de-de/windows/console/peekconsoleinput) which can replace the [WaitForMultipleObjects](https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-waitformultipleobjects) mechanism introduced in #120 and thereby also solve #24 for the Windows Terminal where the mechanism from #120 does not work reliably.

**Comment by meowgorithm** [comment]
Bubble Tea now supports mouse events in Windows in `master`. This functionality will be available in the next release.

As a technical note, we're only processing X10 mouse events, which are fairly basic across the board. It's possible to [`ReadConsoleInput`](https://docs.microsoft.com/en-us/windows/console/readconsoleinput) (mentioned by @erikgeiser above) to gain access to higher fidelity mouse events on Windows.

**Comment by meowgorithm** [comment]
This is now available in [`v0.17.0`](https://github.com/charmbracelet/bubbletea/releases/tag/v0.17.0).
