### ISSUE TITLE
PR #1033 broke the tabs example

### ISSUE THREAD

**Issue by daabr** [charmbracelet/bubbletea#1034]
**Describe the bug**
PR #1033 removed `.Copy()` calls from styles in the tabs sample (https://github.com/charmbracelet/bubbletea/tree/master/examples/tabs).

This causes the borders in the example to appear messed up, because the example modifies them during runtime. Without `Copy()` the example is modifying the same border without cleanup, instead of separate copies of it.

**Setup**
Please complete the following information along with version numbers, if applicable.
 - OS: macOS
 - Shell: zsh
 - Terminal Emulator: iterm2
 - Terminal Multiplexer: n/a

**To Reproduce**
1. Run the tabs example (https://github.com/charmbracelet/bubbletea/tree/master/examples/tabs) before and after PR #1033

**Comment by pikomonde** [comment]
Hi @daabr , can you share an image for this one?

I've tried to reproduce this, but not see any difference.
(up is the latest master, bottom is before the PR)
![image](https://github.com/charmbracelet/bubbletea/assets/32364823/4fa8ee28-236c-4e79-a9d5-e27a98085a47)

**Comment by daabr** [comment]
Confirmed. I used an older version in my `go.mod` file - once I updated, `Copy()` was marked as deprecated, and the code works as expected.
