### ISSUE TITLE
Architectural Advice - Global Model?

### ISSUE THREAD

**Issue by aronchick** [charmbracelet/bubbletea#1082]
Hi--

I'm using Cobra command to execute a series of deployments - think something that merges together deploying to GCP, Azure and AWS under a single command. 

I am absolutely loving bubble tea - i'm wondering what the right pattern is for maintaining the "model". My initial thought:

- In the main cobra command thread, intiialize, and run, the tea program. When it finishes, the application is finished.
- Maintain a global singleton of the model - in every sub command/package, etc, provide a function (GetModel()), that gets a pointer to this singleton.
- Update that singleton with data as various threads add more information.

Is that standard? Other options - all data update functions are instance functions of the model, or passing around pointers to the model? Am I missing anything?

**Comment by decentral1se** [comment]
I don't have all the links / docs / issues etc. when I went down this particular rabbit hole myself but I've settled on "one model to rule them all" including "one view to rule them all" (even on much larger programs, it scales!) and it's just easier to deal with tbh.

This should probably go in https://github.com/charmbracelet/bubbletea/discussions also 😊

**Comment by aronchick** [comment]
thanks! moving over now.

**Comment by agilgur5** [comment]
For reference, this was moved to https://github.com/charmbracelet/bubbletea/discussions/1097
