### ISSUE TITLE
Viewport receives keystrokes from textarea

### ISSUE THREAD

**Issue by rchaganti** [charmbracelet/bubbletea#1106]
**Describe the bug**
When combining viewport and textarea, and when textarea is in focus, typing characters like `b` and `d`, scrolls the viewport content.

**Setup**
 - OS : Windows 11/WSL 2
 - bash

**To Reproduce**
Run the example: [https://github.com/charmbracelet/bubbletea/tree/master/examples/chat](https://github.com/charmbracelet/bubbletea/tree/master/examples/chat)

**Expected behavior**
When textarea is in focus, the keystrokes such as `b` and `d` should not be sent to the viewport.

**Comment by meowgorithm** [comment]
Good call. We've fixed this and cleaned up the example all around. Thanks for raising this issue!

**Comment by rchaganti** [comment]
The changes in the example prevent keys being routed to the viewport. However, it removes the functionality of viewport scrolling. @meowgorithm

**Comment by tyler71** [comment]
@rchaganti I handled this by including a case for specific movements I wanted (key up / down, page up / down)

```golang
case tea.KeyUp, tea.KeyDown, tea.KeyPgUp, tea.KeyPgDown:
	m.viewport, _ = m.viewport.Update(msg)
```
