### ISSUE TITLE
(v2) altscreen takes a second to kick in on startup in tmux

### ISSUE THREAD

**Issue by robinovitch61** [charmbracelet/bubbletea#1159]
**Describe the bug**

Screen jumps around a bit on startup as a result:

https://github.com/user-attachments/assets/3881bb45-4f4d-402f-b8b9-a9dc4aa06bab

**Setup**
Please complete the following information along with version numbers, if applicable.
 - OS MacOS
 - Shell zsh
 - Terminal Emulator: repro'd in tmux on both macos terminal app and iterm2
 - Terminal Multiplexer tmux

**To Reproduce**
* Clone https://github.com/robinovitch61/kl/commit/41cc7ad29f807d9000f3988036deb436191bfeed
* Run `go run .` in a tmux session

**Source Code**
See above

**Expected behavior**
No jumpyness

**Screenshots**
See above

**Additional context**
v2 is exciting!

**Comment by aymanbagabas** [comment]
Hi @robinovitch61, could you please provide a minimal reproducible code? I'm trying to reproduce using the examples in bubbletea/examples but no luch :/

**Comment by robinovitch61** [comment]
> Hi @robinovitch61, could you please provide a minimal reproducible code? I'm trying to reproduce using the examples in bubbletea/examples but no luck :/

Are you able to repro with the link in the ticket, my existing app as example?

**Comment by robinovitch61** [comment]
This seems resolved on the latest v2 alpha, closing :)
