### ISSUE TITLE
(v2) foreground/background color requests don't work in tmux

### ISSUE THREAD

**Issue by robinovitch61** [charmbracelet/bubbletea#1160]
**Describe the bug**
Not sure if this is a real bug or not, i.e. not sure if you want to make a workaround/fix for it, but would be awesome if this could be supported.

**Setup**
Please complete the following information along with version numbers, if applicable.
 - OS [e.g. Ubuntu, macOS] MacOS
 - Shell [e.g. zsh, fish] zsh
 - Terminal Emulator [e.g. kitty, iterm] iterm2
 - Terminal Multiplexer [e.g. tmux] tmux

**To Reproduce**
In tmux, this produces no output:
```
echo -e "\x1b]10;?\x07"
```

So in my bubble tea app, I never get back a foreground/background color message.

**Source Code**
N/A

**Expected behavior**
Get foreground/background color message in tmux.

**Screenshots**
None

**Additional context**

**Comment by aymanbagabas** [comment]
Hi @robinovitch61, Tmux supports fg/bg queries but not cursor i.e. OSC10/OSC11 but not OSC12. I wasn't able to reproduce as both fg/bg work fine on my end. I'm running `tmux 3.4`. Support for this was added in [tmux 3.4](https://github.com/tmux/tmux/blob/master/CHANGES#L63)

<img width="793" alt="image" src="https://github.com/user-attachments/assets/5156fed3-e857-4e9c-b5b1-a5333faed2e3">

**Comment by robinovitch61** [comment]
Thanks, confirmed this works after upgrading - I was on tmux 3.3a. Maybe I'll get my app to print a warning if the user is on a pre-3.4 tmux version with a recommendation to upgrade.
