### ISSUE TITLE
Why not use interfaces?

### ISSUE THREAD

**Issue by thetooth** [charmbracelet/bubbletea#12]
Just found this lib and something that seems a bit off to me is the API with regards to actually implementing your "program".
```go
func NewProgram(init Init, update Update, view View) *Program
```
The setup function firstly takes a number of custom types, now there's nothing wrong with these however when using an editor with intellisense like vscode, the actual meaning of those types is obfuscated and means you have to open the docs or Ctrl+click a few times to know what you're trying to satisfy.

Second, the update and view function also takes our model as a parameter, only it's not really our model now, it's a blank interface so every time I want my data I need to cast it back into the *real* model, check that it wasn't passed something else and then return a copy of it? I would like to know the reasoning behind this as it seems like a bit of a runabout way of doing things.

As an alternative I would propose that `NewProgram` takes an interface that satisfies the library:
```go
type Model interface {
	Init() tea.Cmd
	Update(tea.Msg) tea.Cmd
	View() string
}

func NewProgram(from Model) *Program {...}
```
A program could then be initialised like so:
```go
type myModel struct {
	content  string
	ready    bool
	viewport viewport.Model
}

func (m *myModel) Init() tea.Cmd {...} // Could possibly omit this in favour of a smaller interface?
func (m *myModel) Update(tea.Msg) tea.Cmd {...}
func (m *myModel) View() string {...}

myInstance := myModel{
	content: "hello",
}

p := tea.NewProgram(myInstance)
if err := p.Start(); err != nil {
	fmt.Println("could not run program:", err)
	os.Exit(1)
}
```
Again I have not looked to deeply at the library sources to see anything jump out as to why this would not be possible, I just think this would allow a slightly cleaner API for users and allow for more fancy use cases such as type composition defined views.

**Comment by meowgorithm** [comment]
This is a good idea and certainly feels more like idiomatic Go. Also good points about IntelliSense and avoiding unnecessary assertions. To be perfectly honest, the type assertion on the model in `Update` and `View` have always irked me a bit.

We're going to look into this: I'll let you know once we've started exploring it.

**Comment by meowgorithm** [comment]
Hi! Just a note that we implemented this and it's now in master, with one small adjustment to Update:

```go
```

**Comment by meowgorithm** [comment]
Hi! Just a note that we've implemented this and it's now in master, with one small adjustment to Update:

```go
type Model interface {
    Init() Cmd
    Update(Msg) (Model, Cmd)
    View() string
}
```

For immutability reasons it's important that Update return a copy of the model rather than simply mutate it in place.

Thanks for the suggestion and thoughtful, thorough explanation as to why this update made sense.
