### ISSUE TITLE
Read input events instead of raw bytes in Windows (mouse support/window change events/canceling inputloop)

### ISSUE THREAD

**Issue by erikgeiser** [charmbracelet/bubbletea#121]
**Disclaimer:** This issue is meant to supersede #103 and #24. The proposed change would be based on #120. This issue is based on a comment I made in #103.

Windows supports reading  [INPUT_RECORDs](https://docs.microsoft.com/en-us/windows/console/input-record-str) with [ReadConsoleInput](https://docs.microsoft.com/en-us/windows/console/readconsoleinput). However, this means that the Windows input event parsing logic (which would then be based on [INPUT_RECORD](https://docs.microsoft.com/en-us/windows/console/input-record-str) structs) would have to be decoupled from the Unix logic.

Changing the input handling to use [INPUT_RECORDs](https://docs.microsoft.com/en-us/windows/console/input-record-str)  would allow `bubbletea` to receive [MOUSE_EVENT_RECORDS](https://docs.microsoft.com/en-us/windows/console/mouse-event-record-str) (closing #103). It also enables the usage of [PeekConsoleInput](https://docs.microsoft.com/en-us/windows/console/peekconsoleinput) to augments the [WaitForMultipleObjects](https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-waitformultipleobjects) mechanism introduced in #120 in order to solve #24 for the Windows Terminal where #120 does not work reliably.

[INPUT_RECORD](https://docs.microsoft.com/en-us/windows/console/input-record-str) can also be a [WINDOW_BUFFER_SIZE_EVENT](https://docs.microsoft.com/en-us/windows/console/window-buffer-size-record-str) which sounds like a good replacement for `SIGWINCH` on Windows.

There is also already a [PR for the Go standard library](https://github.com/golang/sys/pull/98#diff-6a5d6dfef9f877a293639aa3898a47ccf1f6be4ad6ce3e5e035d187f671a6e4b) to add [ReadConsoleInput](https://docs.microsoft.com/de-de/windows/console/readconsoleinput) but it has become a bit stale over the last few months. However, we probably need [PeekConsoleInput](https://docs.microsoft.com/en-us/windows/console/peekconsoleinput) to augments the [WaitForMultipleObjects](https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-waitformultipleobjects) anyway so the implementation has to use `windows.NewLazySystemDLL("kernel32.dll").NewProc("...").Call(...)` anyway.

**Comment by erikgeiser** [comment]
After some experimentation I found that it is easily possible to get both mouse events as well as window change events using [ReadConsoleInput](https://docs.microsoft.com/en-us/windows/console/readconsoleinput). However the Go standard library does not help much with that so it is necessary to write a lot of glue code to interface with the Windows API functions.

Good news is I already did just that over at https://github.com/erikgeiser/coninput/ (see also the [documentation](https://pkg.go.dev/github.com/erikgeiser/coninput) and the [example](https://github.com/erikgeiser/coninput/blob/main/example/main.go)).

**Comment by jon4hz** [comment]
Any news on this? It would be pretty cool, if windows input events get handled properly

**Comment by meowgorithm** [comment]
It’s going to be a little bit until we can look into this this one, but it’s definitely something we’re keen to sort out. Ideally, Erik’s library makes this a breeze.

**Comment by meowgorithm** [comment]
Just some housekeeping here: closing this as #140 is now closed. Erik's, thanks again for all your work around this regardless.
