### ISSUE TITLE
running in browser

### ISSUE THREAD

**Issue by 7flash** [charmbracelet/bubbletea#1231]
I think it must be possible by using wasm in xterm.js?

**Comment by bashbunni** [comment]
Someone created an example here, haven't tried it myself though https://github.com/BigJk/bubbletea-in-wasm

**Comment by 7flash** [comment]
> Someone created an example here, haven't tried it myself though https://github.com/BigJk/bubbletea-in-wasm

I tried, thanks, it works very well

**Comment by bashbunni** [comment]
@7flash Awesome, thanks for letting us know!
