### ISSUE TITLE
Navigating between Models

### ISSUE THREAD

**Issue by NickHackman** [charmbracelet/bubbletea#13]
In Elm you can use an Application in order to switch between models/views ([application](https://guide.elm-lang.org/webapps/navigation.html)). 

For more complicated applications how would one do that in Bubbletea? In the views example the views effectively share a Model, but for more complex applications that's not feasible.

**Comment by meowgorithm** [comment]
Bubbletea’s definitely a bit more naïve in that area compared to Elm. What I did in [Glow](http://github.com/charmbracelet/glow) and [Charm](http://github.com/charmbracelet/charm) was delegate to sub-level model, updates, and views based on a top-level state enum:

```go
type state int

const (
	index state = iota
	detail
)

type model struct {
	state  state
	index  indexModel
	detail detailModel
}

func initialize() (tea.Model, tea.Cmd) {
	return model{
		state:  index,
		index:  newIndexModel(),
		detail: newDetailModel(),
	}, nil
}

func update(msg tea.Msg, mdl tea.Model) (tea.Model, tea.Cmd) {
	m, _ := mdl.(model)

        switch msg.(type) {
                // Logic for changing the
        }

	switch m.state {
	case index:
		indexModel, cmd := indexUpdate(msg, m.index)
		m.index = indexModel
                // Potential logic for changing the state could go here…
		return m, cmd

	case detail:
		detailModel, cmd := detailUpdate(msg, m.index)
		m.detail = detailModel
                // Potential logic for changing the state could go here…
		return m, cmd

	default:
		return m, nil
	}
}

func view(mdl tea.Model) string {
	m, _ := mdl.(model)

	switch m.state {
	case detail:
		detailView(m.detail)
	default: // index
		indexView(m.index)
	}
}
```

**Comment by NickHackman** [comment]
Thanks that makes sense, I appreciate the example!

**Comment by meowgorithm** [comment]
Wonderful. We’d love to see anything you happen to build!

**Comment by meowgorithm** [comment]
Hi! Just a small note that we've changed the Bubble Tea API very slightly, which removes the need for type assertions on models and generally feels more like idiomatic Go. As such, I've updated the example above accordingly.

**Comment by Hkyx** [comment]
Hi, nice thread got the issue :). 

For new go users like me, may be you can make a bigger example with multiple value where you call a function from multiple choices or stuff like that ?

**Comment by jpxor** [comment]
Does this mean all models must be created up front?   I just starting learning bubbletea, and was trying to return a new model in the update function, replacing the top level.  It didn't work when trying to pass the filepicker.

I didn't see how to switch between different views in the examples.
