### ISSUE TITLE
Allow to change output Writer

### ISSUE THREAD

**Issue by dankox** [charmbracelet/bubbletea#14]
Hi,
I've come across this library lately while doing som TUI stuff and I really like the approach here.
I'm using mostly Windows 10, but was trying to use it on Windows 7 and there is a bit of problem, because Win7 doesn't support ANSI characters. 
In reality Windows 7 is out of support, so I guess it's no big deal (I will be upgrading too anyway), but I was wondering if it wouldn't be worth to try to add a function which could override the default `output *os.File`. Maybe it's not worth just for that, but could be used also in other cases, when you want to dump it in a file or logger with your specific `Writer` (even though, I'm not sure if that's worth it or useful at all).

What I did was, I tried to run it with some `Program` function like this `p.SetOutput(colorable.NewColorableStdout())`, where `colorable` is `github.com/mattn/go-colorable` package. It allows colors even on older version of Windows console (translating ANSI to API calls to write the output) and makes it more usable. It still doesn't resolve all the problems, but makes some basic stuff work. 
For simplicity, I just split output to original `os.File` for inputs and `io.Writer` for output.

Anyway, this is more like a suggestion or a thing to think about. So it's up to you, if you find it worth it. I don't mind and will definitely use it either way :)

**Comment by meowgorithm** [comment]
Hi! It was always the plan to expose `Program.output` and you're absolutely right that it should be an `io.Writer`. We're looking into this, however I believe we may be limited by the [github.com/containerd/console](https://github.com/containerd/console) package which we’re using specifically for it's particularly good Windows support when it comes to setting the terminal into raw mode. As it is, the package operates explicitly on `os.Stdout` only.

We'll update this thread should we make any progress. Thanks for the suggestion and details and thank you for the kind words about Bubble Tea!

**Comment by meowgorithm** [comment]
Just a note that this has been implemented and is now in `master`. It works like this:

```go
// With custom input
p := tea.NewProgram(model{}, tea.WithInput(customInput))

// With custom input and output
p := tea.NewProgram(model{}, tea.WithInput(customInput), tea.WithOutput(customOutput))
```

Also, input/output have been generalized from `*os.File` to `io.Reader` and `io.Writer`.

We'll close this issue once this is related in Bubble Tea v0.12.3.

**Comment by meowgorithm** [comment]
This is now in [v0.12.3](https://github.com/charmbracelet/bubbletea/releases/tag/v0.12.3).
