### ISSUE TITLE
Development hot reload

### ISSUE THREAD

**Issue by leg100** [charmbracelet/bubbletea#150]
During development, I'd like to be able to make changes to the code and then run the program in order to visually see the results. Of course it gets repetitive:

1) Make changes, save file(s)
2) Run program
3) Repeat

I'd like then a tool that rolls up these steps into just one step: make changes, save file(s); tool automatically restarts program. Ideally the two would run side-by-side on my monitor. 

For example, with web development, there is `livereload.js` which embeds some javascript in the website you're developing, and when you make changes the website page automatically reloads.

Whereas for my bubbletea-based program I've tried using:

* https://github.com/cortesi/modd
* https://linux.die.net/man/1/inotifywait
* https://github.com/eradman/entr

But none of them support running the program with a TTY. The following issue describes the problem (although it concludes it's not an insurmountable problem):

https://github.com/eradman/entr/issues/81

So has anyone found a way to support this particular development feedback loop for programs developed with bubbletea? Or perhaps I'm missing an alternative approach that works just as well?

Note: I appreciate this is no substitute for unit tests.

**Comment by adambabik** [comment]
I am using [watchexec](https://github.com/watchexec/watchexec) like this: 

```
watchexec -r -e go -- "go run ./cmd/stateful/main.go my-command"
```

Each time I change the code it re-prints the output but controls work as expected.

**Comment by maaslalani** [comment]
```
watchexec -r -c -e go -- "go run main.go"
```

Works for me as well!

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
hi there,
sorry to necrobump, but I have trouble successfully doing what you outlined - neither `air` nor `watchexec` seem to be working:
```
% watchexec -r -c -e go -- "go run ."
```
^ this results in absolutely no output on the screen (beyond "[Running: go run -v .]", of course), similar with `air` (actually garbage characters appear):
```
%  air

  __    _   ___
 / /\  | | | |_)
/_/--\ |_| |_| \_ v1.52.3, built with Go go1.22.5

watching .
!exclude tmp
building...
^[]11;rgb:1e1e/1e1e/2e2e^[\^[[28;1R
```
.

what are you using these days?

**Comment by dlvhdr** [comment]
Don't know if it helps, but when using `tmux` you can do something like this:
1. Create a script named `bwatch`
```sh
#!/usr/bin/env bash

echo "Starting bwatch..."
tmux send-keys -t 2 C-c
sleep 0.5
tmux send-keys -t 2 clear C-m
sleep 0.2
tmux send-keys -t 2 "go run ." C-m
sleep 0.2
```
2. Open 3 nvim splits, 1 for Neovim, 1 for the running bubbletea program and 1 for running `bwatch`.
3. Run `bwatch` in the 3rd pane with: `fd --extension go . | entr bwatch`
4. Make changes in Neovim

This works like so:
https://github.com/user-attachments/assets/823120f3-324e-4822-9ca4-2a7c2c38a424

**Comment by git-ival** [comment]
Resurrecting this for future users who may be using a similar dev setup.

Here is the setup I am currently using for my bubbletea project:
WSL 2 (Ubuntu 20.04)
Windows Terminal
Bash 5.2.26
bubbletea v1.2.3
go 1.22.5

With the above config, I needed to pass the `--wrap-process session` option in order for my TUI to actually render. Without this option the program runs but doesn't render any output and doesnt allow user input either.

My full command looks like: 
`watchexec -r -e go --wrap-process session -- "go run ./cmd/mycli/main.go <my subcommands/args>"`

**Comment by mkolibaba** [comment]
Using Windows + WSL, found that `watchexec` works only with `--poll` setting:
```
watchexec -r -c -e go --wrap-process session --poll 1000 -- "go run ./cmd/mycli/main.go <my subcommands/args>"
```

**Comment by dhnaranjo** [comment]
https://github.com/mitranim/gow works great for me, as easy as `gow run ./cmd/thing`. Linux, NixOS, in a flake dev shell.
