### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by ii64** [charmbracelet/bubbletea#153]
Hello i tried to input unicode but it is not recognized by bubbletea, Thank you.
`go version go1.17 windows/amd64`

![image](https://user-images.githubusercontent.com/26342994/140540833-aed18385-878d-4861-842b-5ac26e485c81.png)

![image](https://user-images.githubusercontent.com/26342994/140540986-e98a4381-0b6f-4995-8da5-0a1ba5341522.png)
![image](https://user-images.githubusercontent.com/26342994/140541013-6fdd67fa-e076-4842-baa3-d44c89984108.png)

```go
type tuiModel struct {
	p string
}
func (m *tuiModel) Init() tui.Cmd {
	return func() tui.Msg {
		return nil
	}
}
func (m *tuiModel) Update(msg tui.Msg) (tui.Model, tui.Cmd) {
	switch msg := msg.(type) {
	case tui.KeyMsg:
		return m.handleKeyboardInput(msg)
	}
	return m, nil
}
func (m *tuiModel) View() string {
	return m.p
}
func (m *tuiModel) handleKeyboardInput(msg tui.KeyMsg) (tui.Model, tui.Cmd) {
	switch msg.String() {
	case "ctrl+c":
		return m, tui.Quit
	}
	m.p = m.p + fmt.Sprintf("\n%s （%+#v）", msg, msg)
	return m, nil
}
```

**Comment by meowgorithm** [comment]
Hi! Unicode and IME is supported supported by Bubble Tea. What's your system locale set to? Sometimes we've seen this happen when the locale isn’t UTF-8, particularly with CJK locales.

Also, the quick solution is often to set your system locale to UTF-8. On my English/US version of Windows 11 that’s: Control Panel -> Clock and Region -> Region -> Administrative Tab -> Change system locale… -> Beta: Use Unicode UTF-8 for worldwide language support.

**Comment by jon4hz** [comment]
I've run into issues using unicode symbols on windows (cmd & powershell but not windows terminal). I suppose both don't support the full char set by default. Is there a way to check, if the terminal supports certain chars?

**Comment by ii64** [comment]
Okay i got `Beta: Use Unicode UTF-8 for worldwide language support` enabled, restarted my computer, but problem remain the same :/. 

【我愛你】 converted to `tea.KeyMsg{Type:-1, Runes:[]int32{0, 0, 0}, Alt:false}`.

![image](https://user-images.githubusercontent.com/26342994/141670286-ebd2bd98-15e9-4149-a0a4-3a8654885a46.png)
![image](https://user-images.githubusercontent.com/26342994/141670356-f8ed9816-6ec9-42bf-ba09-cc0035429fec.png)

**Comment by knz** [comment]
I think this was fixed in #343. Can you check?

**Comment by buffos** [comment]
I am having the [same problem](https://github.com/charmbracelet/huh/issues/203) (when using huh). They are probably related.
There is no support for Greek characters in input fields. Utf-8 is enabled.

**Comment by meowgorithm** [comment]
Hi! This is specific to Windows and should be fixed on `master`.

```go
go get github.com/charmbracelet/bubbletea@master`
```

If that's not the case, please re-open the issue. Thanks!
