### ISSUE TITLE
Filter search not working in list-simple example

### ISSUE THREAD

**Issue by souvikinator** [charmbracelet/bubbletea#155]
After running the example [list-simple/main.go](https://github.com/charmbracelet/bubbletea/blob/master/examples/list-simple/main.go) I noticed that the search function is not getting triggered. 

I see the [FilterValue()](https://github.com/charmbracelet/bubbletea/blob/a55bf775cd3fb2418d6ac3498a7792d773b8643e/examples/list-simple/main.go#L26) is also defined just like in other list examples.

Not sure if this is the default behavior or some issue.

## Edit

`l.SetFilteringEnabled(true)` setting this to true enables the search but now the issue is it shows nothing in the search like so:

![issue-bubble](https://user-images.githubusercontent.com/64456160/140871788-00775c3c-c762-4c60-8d0b-ea3bec2ed73d.gif)

**Comment by meowgorithm** [comment]
Hi! So the list example was actually intended to have filtering disabled, but it looks like we accidentally left some of the filtering hooks in. We’ll remove it to keep the simple example simple.

That said, [here is the simple list example](https://gist.github.com/meowgorithm/90b3b645f8a82196442a72b5e0cf61ba) with filtering enabled and [here is the diff with the necessary changes](https://gist.github.com/meowgorithm/90b3b645f8a82196442a72b5e0cf61ba/revisions). Basically, you just need to make sure the <kbd>enter</kbd> doesn't select an item while filtering and then you just need to make sure all messages pass through list’s `Update` function so filter matching messages will be processed.

On that note (and to your point, @jon4hz) `list.filterMatchesMsg` should probably be exposed so people can match on that message.

**Comment by souvikinator** [comment]
Hey there! thanks for clarifying. So I was trying to update the list contents in `View` rather than `Update`. Now it's working, thanks for pointing out :)

**Comment by jon4hz** [comment]
@meowgorithm if you want filtered disabled in the simple-list example I'll close my PR. Exposing `list.filterMatchesMsg` is imo a cool idea.
