### ISSUE TITLE
Where to look for components?

### ISSUE THREAD

**Issue by thunderrous** [charmbracelet/bubbletea#159]
Sorry for such a question but I'm kind of lost in the docs as to where I'm supposed to look for docs on components like the list item, buttons, labels etc?

I want to make something to make bulk transferring files over MTP (to Android phones) easier and I'd like to use your library because of its aesthetics but have no idea where to start.

Thanks.

**Comment by muesli** [comment]
The components (so called "Bubbles") can be found here: https://github.com/charmbracelet/bubbles

Each bubble typically comes with at least one example (often more), which should get you started. Additionally you can find the API docs here: https://pkg.go.dev/github.com/charmbracelet/bubbles

I can also recommend checking out a bunch of the existing apps that use bubbletea/bubbles. They're often a great inspiration!

**Comment by thunderrous** [comment]
@muesli thanks for answering. Is there something like treeview? I need to display a file tree and have the user select files/folders.

**Comment by muesli** [comment]
@thunderrous I'm afraid we don't have a full featured treeview yet.

With that being said, `fm` is a file manager - built with bubbletea - that uses a two-pane view to navigate through a hierarchy of directories. Maybe that's helpful to you? Check it out: https://github.com/knipferrc/fm

**Comment by thunderrous** [comment]
Yeah I saw it already. Thanks.
