### ISSUE TITLE
Automatically set correct color profile

### ISSUE THREAD

**Issue by antonmedv** [charmbracelet/bubbletea#172]
I want to create something like fzf. The fzf renders to stderr, while returning content to stdour.
So next is possible (fzf will open interactive TUI):
```
fzf | cat
```

But termenv do this by default: 
```go
func ColorProfile() Profile {
	if !isatty.IsTerminal(os.Stdout.Fd()) {
		return Ascii
	}

	return colorProfile()
}
```

I know what I can manually call `lipgloss.SetColorProfile`, but it will be cool if creating stderr apps will be easy, and the next code just work:

```go
p := tea.NewProgram(m, tea.WithOutput(os.Stderr))
```
But now I need to copy-paste `colorProfile()` logic to be able to detect the correct profile.

Thanks!

**Comment by meowgorithm** [comment]
That's a great suggestion. Thank you!

**Comment by muesli** [comment]
I need to check if that's really possible. The OSC queries are meant to be transferred via `stdout`, but we can certainly see how terminals react to them being written on `stderr`.

**Comment by antonmedv** [comment]
Maybe use or adapt this Sindre’s nodejs port: https://github.com/jwalton/go-supportscolor

**Comment by muesli** [comment]
> Maybe use or adapt this Sindre’s nodejs port: https://github.com/jwalton/go-supportscolor

`termenv` (and hence `lipgloss`) is already doing that (and more) internally, and that operation doesn't depend on stdout vs stderr. This issue would only affect detecting the terminal's current color scheme.

That being said, I've recently did some work on `termenv` that lets you write to different file descriptors like `stderr`: https://github.com/muesli/termenv/tree/termenv-next
