### ISSUE TITLE
Tea with Alt screen gets messed up after openning sub command.

### ISSUE THREAD

**Issue by antonmedv** [charmbracelet/bubbletea#173]
Hi,

I'm starting tea with:
```go
p := tea.NewProgram(m, tea.WithOutput(os.Stderr))
```

Then in Update() call sub process:
```go
				cmd := exec.Command("vim")
				cmd.Stdin = os.Stdin
				cmd.Stdout = os.Stderr // Render to stderr.
				m.editMode = true
				_ = cmd.Run()
				m.editMode = false
				return m, tea.HideCursor
```

After the exit of vim tea program all messed up and no alt screen in place. 

Not sure if it is supported at all. Please, help me to debug. Trying to add AltScreen to https://github.com/antonmedv/llama.

Thanks! 🙏

**Comment by meowgorithm** [comment]
Noted, thank you. This is definitely something we'd like to support, though it may require some research.

Curious: why are you printing to `stdout` rather than `stdin`?

**Comment by antonmedv** [comment]
It’s because of llama integration: cd $(llama)
Stdout used to carry data to cd.

**Comment by meowgorithm** [comment]
I'm going to close this issue because it's so close to #171, especially because when we do end up we solving this we'll need to support this functionality for Bubble Tea applications that use alt screen regardless.

@antonmedv, let me know if you feel differently and would prefer to keep this open.
