### ISSUE TITLE
PowerShell windows resize

### ISSUE THREAD

**Issue by antonmedv** [charmbracelet/bubbletea#174]
Hi,

I'm playing with the new Windows Terminal and PowerShell. And looks like something is wrong with resizing there.

Here is what I'm getting after resizing the terminal in llama. 
![Снимок экрана (3)](https://user-images.githubusercontent.com/141232/146657960-1465f18e-595f-4371-9749-433718abf0ed.png)

**Comment by antonmedv** [comment]
cmd.exe resize also not works.

**Comment by antonmedv** [comment]
Git Bash for windows not working either.

**Comment by meowgorithm** [comment]
Thanks for posting. Windows resizes are currently unsupported because Windows doesn’t implement the `SIGWINCH` signal.

Once #140 is merged, however, resizes should work on Windows.

**Comment by meowgorithm** [comment]
@antonmedv I’ll see what needs to happen for #140 to get merged. My understanding is that it’s ready to go and we generally just need to test it out. Feel free to check it out as well.

**Comment by antonmedv** [comment]
Awesome! Thanks for your not easy work on this project) Will test it definitely as I'm willing to port llama to win as well.
