### ISSUE TITLE
Allow unmanaged console output

### ISSUE THREAD

**Issue by rfc2119** [charmbracelet/bubbletea#179]
Using bubbletea, I would like to have a progress bar similar to `apt`'s:
![apt-progress-bar](https://user-images.githubusercontent.com/4954847/147839573-e081ce74-2908-455e-af17-5ca1af3969ec.png)

Progress bar is updated and the above text does not get cleared. I could not achieve this in bubbletea. The closest attempt I got resulted in an unexpected error (see this [cast](https://asciinema.org/a/V15hrCBa6p9n6U8AHkSde7kkN). the code is a modification of _examples/spinners/main.go_). 

I have also tried using `bubbletea.ScrollDown()` but it instantly clears the screen. Any ideas ?

**Comment by meowgorithm** [comment]
This is a good one definitely a feature we’d like to support, however to do so we’ll need to add some additional functionality to both to the renderer as well as probably a special `Cmd` for unmanaged output.

Anyway, his should be a fun one. We’ll keep this issue updated with progress.

**Comment by rfc2119** [comment]
Thanks for your input @meowgorithm ! If there's anything I can help with, please do not hesitate to ask. I will try to help as much as I can

**Comment by Adjective-Object** [comment]
I have a working approach to this. I tested it out by exposing the `renderer` interface and allowing client programs to replace the renderer with a custom implementation.

Changes to expose the renderer: https://github.com/charmbracelet/bubbletea/pull/246
The renderer: https://github.com/Adjective-Object/tea_log_renderer/blob/main/tea_log_renderer.go

Happy to PR this in @meowgorithm. If you're ok with this approach, let me know if you'd prefer the to keep the Renderer internal and I can make this a feature flag on the standard renderer.

**Comment by meowgorithm** [comment]
Thanks for the info (and the PR!), @Adjective-Object. I'm inclined to keep the rendering interface internal for now as it (somewhat intentionally) hasn't been given the attention necessary for a public API. However, at a glance, your implementation seems to make sense.

Would you be interested in submitting a PR against the standard renderer instead? I've been imagining the public interface as a `Cmd`  or two, perhaps something like:

```go
// A command for printing above the output, with a final newline
func Println(...string) Msg

// A command for printing above the output, probably also with a newline (somewhat like log.Print)
func Printf(string, vars ...string) Msg
```

I'd also _probably_ leave word-wrapping as an exercise for the user, but open to your opinions here.

Let me know what you think!

**Comment by Adjective-Object** [comment]
I'm happy to open a PR against the standard renderer.

I'm of a split mind on whether to wrap or truncate printed lines.
I struggle to think of a time I'd personally want to log "as if with
println" without wrapping. But for the sake of consistency with the rest of
the renderer I'm leaning towards truncating lines.

What do you think the behaviour of the Println() Cmd should be when in
AltScreen mode? I don't see a clean way to get an error tonth user somehow
so the only option I can see is dropping the messages silently.

And thanks for the cool framework! This has been a joy to hack on :)

**Comment by Adjective-Object** [comment]
Revisiting this : is there a convenient place for consumers to get access to the widthe of the terminal for word wrapping themselves?

**Comment by meowgorithm** [comment]
> Is there a convenient place for consumers to get access to the widthe of the terminal for word wrapping themselves? Otherwise it might actually make sense as an option when calling Println / Printf, for ergonomics

Yep, via a [`WindowSizeMsg`](https://pkg.go.dev/github.com/charmbracelet/bubbletea#WindowSizeMsg), which is sent to update once on initialization and for window resizes.

**Comment by meowgorithm** [comment]
> What do you think the behaviour of the Println() Cmd should be when in AltScreen mode?

I’d simply not print anything and note in the doc comment that `Printf`/`Println` won’t work when the altscreen is active..
