### ISSUE TITLE
Keyup events

### ISSUE THREAD

**Issue by cwqt** [charmbracelet/bubbletea#186]
Would be super nice to have key released events to be published

**Comment by meowgorithm** [comment]
Unfortunately, unix-based terminals don’t send any data when keys are released. This may be possible in Windows (see #140) however if we can’t offer release events in a cross-platform manner, we’re unlikely to offer them in a Windows-only fashion.

**Comment by cwqt** [comment]
Ah I wasn't aware of this, no worries then
