### ISSUE TITLE
Add dlvhdr/gh-prs to the list of tools built with bubbletea

### ISSUE THREAD

**Issue by dlvhdr** [charmbracelet/bubbletea#188]
Hi :) I created a CLI tool with bubbletea and would like it to be added to the list of tools in the README:
[dlvhdr/gh-prs](https://www.github.com/dlvhdr/gh-prs)

**Comment by muesli** [comment]
"Fix" coming up in #189. Well deserved, we love gh-prs! Keep up the great work! :heart:

**Comment by muesli** [comment]
Merged!

**Comment by dlvhdr** [comment]
Thank you @muesli!
