### ISSUE TITLE
prepare console: set console mode: Paramètre incorrect

### ISSUE THREAD

**Issue by bussiere** [charmbracelet/bubbletea#202]
Here is my configuration Windows Seven 32 bit

and with this example :  

https://github.com/charmbracelet/bubbletea/blob/master/examples/mouse/main.go

and i have this error :  

> 
> ←[?25l←[?1049h←[0;0H←[?1003hDo mouse stuff. When you're done press q to quit.
> 
> ←[3;0H2022/01/25 08:24:27 prepare console: set console mode: Paramètre incorrect

I can understand that you won't support this platform. Thanks for the project btw

**Comment by muesli** [comment]
I think Windows only re-introduced ANSI support with the Windows 10 release. You could probably another terminal (the official Windows Terminal might work) and should be able to run Bubble Tea programs.
