### ISSUE TITLE
Share cancel reader maintenance burden?

### ISSUE THREAD

**Issue by hinshun** [charmbracelet/bubbletea#224]
Thank you @erikgeiser for contributing the cancel reader, I've been looking for this for a while.

I wanted to use this in two other projects and I'm sure many people want it too, curious if @erikgeiser is open to hosting this repository so that it's usable outside of bubbletea?

I've created a temporary repo here making the interfaces public with bubbletea's MIT license:
https://github.com/hinshun/cancel
Happy to transfer ownership to whoever.

I have use for it in two other projects:
- https://github.com/Netflix/go-expect/pull/29

**Comment by muesli** [comment]
Already done here: https://github.com/muesli/cancelreader - happy to accept PRs!

Also see #222.
