### ISSUE TITLE
Q: overlay box

### ISSUE THREAD

**Issue by 76creates** [charmbracelet/bubbletea#238]
Hey all, is it possible to draw a box using x/y coordinates that would overwrite whatever is under it, say another box?
Like having spawing `bar` over `foo`:
~~~
|-----|
|     |
| foo |
|     |
|-----|
~~~
~~~
|-----|
|     |
| foo |
|   |-----|
|---|     |
    | bar |
    |     |
    |-----|
~~~

Thanks!

**Comment by meowgorithm** [comment]
Hi again! This is a feature currently in development. There's no time frame yet, but it'll be implemented in Lip Gloss (see https://github.com/charmbracelet/lipgloss/issues/65) with additional support in Bubble Tea (https://github.com/charmbracelet/bubbletea/issues/79). We'll keep those issue updated with progress. Lip Gloss will likely come first, with Bubble Tea following shortly thereafter.

**Comment by pnsvk** [comment]
can you please post the updates (if any) on this ? its more than 2 years now.
