### ISSUE TITLE
accessing Stdout

### ISSUE THREAD

**Issue by tgirod** [charmbracelet/bubbletea#267]
For an application that is not using AltScreen, is it safe to have a `tea.Cmd` that writes stuff to Stdout, or could it break the display somehow with some unfortunate concurrent access?

**Comment by tgirod** [comment]
Trying to answer this myself with pull request #268

**Comment by meowgorithm** [comment]
Hi there! This is definitely a feature we'd like to see. There are a number of subtle nuances to getting this right, particularly working in-step with the renderer. That said, there's an open PR for this (#249) which I believe is close, if not there.

Want to give that a try and chime in as to whether or not it's working for you?

**Comment by meowgorithm** [comment]
(Also closing as this is a dup of #179.)
