### ISSUE TITLE
Add example: how to work with multiple lists in different tabs

### ISSUE THREAD

**Issue by bashbunni** [charmbracelet/bubbletea#277]
Hey, everyone. And, @sspaink, thank you the PR. We’ve been a little backed up this month, but we’ll get to this one.

In terms of the tabs-of-lists example, why don’t we do this:

1. Keep this example as-is so that people can get a quick understanding of how to work with tabs in Bubble Tea.
2. Add a separate example (in a separate PR) illustrating how to work with multiple lists in different tabs as suggested above.

_Originally posted by @meowgorithm in https://github.com/charmbracelet/bubbletea/issues/181#issuecomment-1029082226_

**Comment by SAVE-POlNT** [comment]
Hello , i wanted to know if this is done or not yet 
i actually plan to make a cli tool that has the same layout like the one you made for the git server 
i looked at the code but im relatively new to go and the framework so i got list 

i suggest a todo list with a group list at the left and todos at the right this will help a lot of ppl getting started with it

**Comment by bashbunni** [comment]
Hi @Mehdi-YC I'm not sure I'm understanding your question. Do you mind re-phrasing?

**Comment by Mehdi-YC** [comment]
lol, for some reason , i did not understand what i said too ,

what i wanted to say is , the layout that you made for the git server cli app is good and useful in a lot of situations

it would be great if we had an example of a simple "todo app"
with a similar layout

like with no external logic evolved other than making the layout usable and easily modifiable.

**Comment by Mehdi-YC** [comment]
Thank you , i already follow what you are making in this channel

**Comment by bashbunni** [comment]
Hey, I believe this was answered in a discussion: https://github.com/charmbracelet/bubbletea/discussions/317
Let us know if that's not quite what you were asking!

**Comment by Mehdi-YC** [comment]
Hello , yes it is what i was searching for , im waiting for the tutorial , ty

**Comment by bashbunni** [comment]
Sounds good, I'll let you know when we post it and will keep this issue open in the meantime

**Comment by titanventura** [comment]
Hey @bashbunni , is this example done ? If not I would like to take this up !

**Comment by bashbunni** [comment]
@titanventura ah it is, I just need to film the video for it. I'll actually close this issue and just track it with the other video ideas I have in queue so it isn't confusing
