### ISSUE TITLE
Handle `CSI u` Input (aka fixterms)

### ISSUE THREAD

**Issue by meowgorithm** [charmbracelet/bubbletea#293]
It would be nice for Bubble Tea to support the "CSI u" Encoding Specification as outlined in Paul Evans' seminal work ["Fix Keyboard Input on Terminals - Please"](http://www.leonerd.org.uk/hacks/fixterms/).

References:
* [Wezterm](https://wezfurlong.org/wezterm/config/lua/config/enable_csi_u_key_encoding.html)
* [Kitty](https://sw.kovidgoyal.net/kitty/keyboard-protocol/)
* [Windows Terminal](https://github.com/microsoft/terminal/issues/8719)
* [iTerm2](https://iterm2.com/documentation-csiu.html)

Special thanks to @imsnif for the suggestion.

**Comment by ghostsquad** [comment]
Yes please!

**Comment by meowgorithm** [comment]
Closing this in favor of https://github.com/charmbracelet/bubbletea/issues/869 which is mostly compatible with [fixterms](http://www.leonerd.org.uk/hacks/fixterms/).
