### ISSUE TITLE
Rendering lines taller than the window height causes mis-renders

### ISSUE THREAD

**Issue by meowgorithm** [charmbracelet/bubbletea#297]
Currently, if you send more lines than the height of the window Bubble Tea rendering flips out. For cases like this we should _probably_ drop lines from the top and keep only the bottom ones.

Thanks to @fiws for flagging this and @maaslalani for reminding us about it.

**Comment by anacrolix** [comment]
I've run into this, it's pretty severe! I previously used https://github.com/vbauerster/mpb which didn't have this problem (for 100s and 100s of lines of content).

**Comment by anacrolix** [comment]
A workaround is to catch `WindowSizeMsg` and limit the lines of output to the `Height`.
