### ISSUE TITLE
Reopen tty issues

### ISSUE THREAD

**Issue by antonmedv** [charmbracelet/bubbletea#302]
Hi! 

I encountered some strange issue with my project: https://fx.wtf

If I do go run, everything works.
```
node -e 'console.log(123)' | go run .
```

But if I do 
```
go install
node -e 'console.log(123)' | fx
```

Suddenly bubbletea can't get any keystrokes. 

<img width="837" alt="Снимок экрана 2022-04-22 в 11 56 46" src="https://user-images.githubusercontent.com/141232/164683970-2d82c3da-749e-4dee-bdf3-608cd7a6b360.png">

I susspect stdin was closed? 

In nodejs project  was able to reopen tty via something like this: https://github.com/indutny/reopen-tty

**Comment by antonmedv** [comment]
I think I figured it out. 

Node somehow closes stdout after some delay after program exits. With go run there is some delay before tea will reopen tty.

With compiled binary there is no delay. Tea reopens tty, node closes tty.

I was able to solve it via adding delay:
```
time.Sleep(100 * time.Millisecond)
p := tea.NewProgram(m, tea.WithAltScreen(), tea.WithMouseCellMotion())
```

Will be cool, if bubbletea can detect stdin what stdin was closed and reopen it.

**Comment by muesli** [comment]
The sleep might be problematic, as there's no guarantee how long node will take to finish/release `stdin`.

**Comment by antonmedv** [comment]
With tea.WithInputTTY() I observed really strange behavior. The first call to fx works as expected. But second, for some reason is broken. And all consecutive also broken.

But if I run `go install` again - first call works! 

I can't understand why? My debugging skills are not enough here.
