### ISSUE TITLE
capture ctrl+Home/End keys

### ISSUE THREAD

**Issue by utku-caglayan** [charmbracelet/bubbletea#310]
It would be great if we can capture ctrl+Home/End key combinations. This work most probably will depend on improvements from #293

**Comment by ghostsquad** [comment]
_yes please_

**Comment by Bwahharharrr** [comment]
I just saw this after adding #369  .. so +1

**Comment by meowgorithm** [comment]
Hi! This may or may not be possible depending on limitations of terminals, but we'll look into it.

Also note that it does not depend on #293.

**Comment by knz** [comment]
would be fixed by #396.
