### ISSUE TITLE
Bit literals in mouse.go break build on pre-1.12

### ISSUE THREAD

**Issue by lttlrck** [charmbracelet/bubbletea#33]
https://github.com/charmbracelet/bubbletea/commit/02a0509e34c3ed74da7933f98cf6863fc41f42dc broke builds on pre-1.12 environments. 

```
/gocode/src/github.com/charmbracelet/bubbletea/mouse.go:70:16: syntax error: unexpected b0000_0100, expecting semicolon or newline or )
```

Any chance you could control this using build tags?

**Comment by muesli** [comment]
We're actually targeting Go 1.13 at this point. I'm not sure it's still worth introducing build tags for something like that. We could switch to a different notion, but that would make the code a little less readable.

**Comment by lttlrck** [comment]
Ok. I'll roll back for now and think about alternatives. Maybe we can bump go versions.

**Comment by muesli** [comment]
Hopefully that's not too much of a hurdle. I assume you were using 1.12 before?

**Comment by lttlrck** [comment]
1.12.9 ... so not a big jump to make. It'll be fine. Thanks.
