### ISSUE TITLE
tea.WithAltScreen() allows scrollback and thus the rendering of undesirable content from the main buffer

### ISSUE THREAD

**Issue by dcominottim** [charmbracelet/bubbletea#349]
Hello there! Absolutely awesome project! <3

I believe the behavior described in the title is a bug as per what I've researched (e.g: for reference, see https://github.com/xtermjs/xterm.js/issues/802) and the fact it blocks bubbletea users from making proper full screen apps similar to vim etc. Right now, this is a big blocker for the app I am developing.

The issue can easily be seen with any examples from the docs, such as the one for TextInput, for instance. I am starting the program with

`	p := tea.NewProgram(initialModel(), tea.WithAltScreen())
`

**Comment by lrstanley** [comment]
@dcominottim what terminal are you using? From my testing on Windows Terminal and a few others, enabling mouse events (haven't tested motion), captures the scroll. The scrollbar, if manually used, does still let me scroll up in some of them, however it seems it's the same behavior with Vim for the ones where it lets me manually scroll up.

**Comment by dcominottim** [comment]
@lrstanley, thanks a lot for your comment. Indeed, I double checked in MacOS with the standard terminal app and have confirmed the behavior that you described. I believe I missed this the first time because the default terminal app hides the scrollbar and doesn't enable scroll back using just the touchpad in this case — but if manually going for the scrollbar, it is as you said. Therefore, I am going to close the issue. Thanks again!
