### ISSUE TITLE
Using tea.WithAltScreen(), after the initial rendering of tea programs, resizing the terminal to a smaller size and then bigger sizes renders repeated/garbage content

### ISSUE THREAD

**Issue by dcominottim** [charmbracelet/bubbletea#350]
Here is a small recording using the code from the TextInput example plus tea.WithAltScreen(). Using MacOS Monterey.

![tea bug](https://user-images.githubusercontent.com/4914233/174460373-4e4ac296-a68f-403e-93fe-507ddddd4dba.gif)

**Comment by Enchufadoo** [comment]
Same issue, Manjaro Linux

![bubbletea_resize](https://user-images.githubusercontent.com/1263356/180624818-47b33943-197c-4ffb-a682-6479e9d08431.gif) 

My repo:  https://github.com/Enchufadoo/launshr

**Comment by 4cecoder** [comment]
This is a dup of https://github.com/charmbracelet/bubbletea/issues/297

**Comment by maaslalani** [comment]
We'll track this in #297
