### ISSUE TITLE
README for the examples page

### ISSUE THREAD

**Issue by shivan-s** [charmbracelet/bubbletea#351]
Hello all,

First, I want to say how cool this package is! From the community to the actual library and ecosystem. I'm very excited to crack on and make some TUIs!

This issue pertains to the suggestion in the documentation.

Do you think it will be beneficial to have a `README.MD` for the examples page and have videos demonstrating each example?

I'm happy to contribute. It helps me learn the various features of `bubbletea`.

Thanks in advance.

**Comment by maaslalani** [comment]
Hey @shivan-s, this is a great idea!

We will soon add GIFs which will also act as a good testing suite since they will be programatically created.

See: https://github.com/charmbracelet/bubbletea/pull/355#issuecomment-1219709267

**Comment by bashbunni** [comment]
Hey @maaslalani do you think we should wait on this until we're also ready to add GIFs or should I go ahead and work with Shivan on getting this up and running?

**Comment by bashbunni** [comment]
Hey @shivan-s if you'd like to get started on this, please feel free! We can also arrange a time to pair program on it if you'd like any help explaining what each example is doing.

**Comment by shivan-s** [comment]
Hey @bashbunni, thanks for picking this up again.

I worked on this: https://github.com/shivan-s/bubbletea/tree/shivan-s-example-added-docs/examples.

Let me know what you think. It was originally submitted as PR #355, I can resubmit the PR (+ I think more examples have been created since then).

**Comment by bashbunni** [comment]
Goals:
- [ ] Give a one-liner description of the examples (some of the names aren't super descriptive)
- [ ] include programatically-generated GIFs
