### ISSUE TITLE
bug: windows missing mouse events past column 95

### ISSUE THREAD

**Issue by lrstanley** [charmbracelet/bubbletea#359]
Running the [mouse](https://github.com/charmbracelet/bubbletea/blob/master/examples/mouse/main.go) example on powershell, Windows Terminal, cygwin-style terminals, and potentially others, doesn't seem to let me capture mouse events beyond column 95. I haven't tested on a proper linux environment yet

Example video: https://ls-screen.s3.us-west-004.backblazeb2.com/2022/07/WindowsTerminal_ninSH9gbiM.mp4

Looking into this further, I did find [this issue comment](https://github.com/microsoft/terminal/issues/545#issuecomment-509436962), which mentions the following:
> The legacy, byte-based protocol only allows row and column numbers up to 223, because 32 is added to this number and this is sent as a single byte. The column limit is not uncommon to be too small. (By the way, **beginning at column 95 the generated data is not 7-bit clean and not valid UTF-8** which is a problem for encoding conversion layers such as luit.)

Specifically:
> beginning at column 95 the generated data is not 7-bit clean and not valid UTF-8

That issue was closed and features implemented, mentioning `SGR 1006 extension`, however I'm not sure if it's something on my end, something on Windows end, or an issue with bubbletea. 😅 

This SO post is unrelated to bubbletea/windows terminal, but also seems to explain the mouse events (legacy vs 1006) to me a little bit more: https://stackoverflow.com/a/5970472/1830159

Any pointers?

**Comment by lrstanley** [comment]
Actually, I don't know why I didn't think to test another application, but it looks like Vim also has a similar issue when enabling mouse mode, so I don't think it's a bubbletea issue. Though I'm still curious if anyone has any pointers (ha!) on what the issue could be. I've got the latest Windows Terminal version, and the latest Windows 10 update, and I can't seem to find others with related issues when searching, so I'm at a loss.

**Comment by lrstanley** [comment]
Just in case anyone else runs into similar issues, upgraded to Windows 11 recently, and the issues disappeared, so I'm guessing something related to WSL2 and Windows 10. Going to close out.

**Comment by muesli** [comment]
Oh wow, that's unexpected and great to hear! Thanks for the feedback!

**Comment by DerpyDashie** [comment]
#594 should fix this
