### ISSUE TITLE
split-editors example jumpins on limited vertical space

### ISSUE THREAD

**Issue by golonzovsky** [charmbracelet/bubbletea#366]
when vertical space is limited tab action makes editor jump out of window until next redraw:
![editor](https://user-images.githubusercontent.com/2477950/178466554-a88cf30b-4f25-4b88-9c25-bd712f4abc42.gif)

Upd: same happens during first draw afer start

**Comment by maaslalani** [comment]
Hey @golonzovsky, thank you for this issue! Should be fixed with https://github.com/charmbracelet/bubbletea/pull/406
