### ISSUE TITLE
suggested utility libraries alongside "Bubble Tea in the Wild"

### ISSUE THREAD

**Issue by lrstanley** [charmbracelet/bubbletea#368]
Hello! I've made a library to help with mouse event tracking, allowing zones to be created, and easily check if mouse events are within a specific zone -- primarily useful for things like tabs, lists, buttons, etc. The goal being to avoid having to do all of the complex offset calculations for mouse events to see which component is being targeted. I'd like to get it added to a suggested list of utility libraries, however looking at the various family of repositories (bubbletea/lipgloss/bubbles/etc), I'm not sure where it's best suited. It's not a built application, a style library, or a component library, moreso a utility library like termenv/reflow/etc.

Would it be ok if I made a PR, adding a new section under "Libraries we use with Bubble Tea" suggesting alternative libraries as well? (I don't want to put it under that specific section directly as I think that'd be a bit misleading).

Project link: https://github.com/lrstanley/bubblezone

Example of the library in action (only wraps existing components, doesn't make its own):
![full-lipgloss example](https://ls-screen.s3.us-west-004.backblazeb2.com/2022/07/WindowsTerminal_tirP0rGZ2z.gif)

**Comment by meowgorithm** [comment]
Dude, this looks amazing. By all means, please do send a PR.
