### ISSUE TITLE
ctrl+pgup, ctrl+pgdown

### ISSUE THREAD

**Issue by Bwahharharrr** [charmbracelet/bubbletea#369]
Things like shift+t  (browser new tab, makes sense to make a 'new tab' support in tui via same key combo
Also, crtl+pg up  or ctrl+pg down

**Comment by meowgorithm** [comment]
Hey, @Bwahharharrr! <kbd>shift+t</kbd> is supported (it comes in as a literal capital `T`):

```go
// Here's what shift+t looks like
tea.Key{type: tea.KeyRunes, runes: []rune{'T'}}

// Matching on it in an update:
func (m model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
    switch msg := msg.(type) {
        case tea.KeyMsg:
            switch msg.String() {
                case "T":
                // shift+T!
        }
    }
    // ...
}
```

As for <kbd>ctrl+pgup</kbd> and <kbd>ctrl+pgdown</kbd>, iirc they're not matchable because of terminal limitations beyond our control, but it's worth looking into again.

**Comment by Bwahharharrr** [comment]
Yeah I only thought about pgup and pgdown because of the familiarity using them in browser tabs, so using the same commands in tui tabs also makes sense.

**Comment by muesli** [comment]
Turns out this is actually parseable from the input stream. Fix in master.
