### ISSUE TITLE
TextArea resize issue

### ISSUE THREAD

**Issue by jamesthesken** [charmbracelet/bubbletea#377]
**OS:** macOS Big Sur 11.6.5

This is an issue with the new textarea bubble. Unsure if this is a Mac specific issue, but the screen capture is attached.

After resizing the window in the [chat example](https://github.com/charmbracelet/bubbletea/blob/master/examples/chat/main.go), the input prompt continuously prints and fills up the remainder of the screen. 

Thank you!

**cc** @maaslalani 

https://user-images.githubusercontent.com/22358037/179902352-aa6c2c3f-93ff-4d72-8c01-10ae3371a057.mov

.

**Comment by dcominottim** [comment]
Probably the same root cause as #350.

**Comment by 4cecoder** [comment]
This is a dup of https://github.com/charmbracelet/bubbletea/issues/297

**Comment by maaslalani** [comment]
We'll track this in #297
