### ISSUE TITLE
`cancelreader.NewReader`  not support chinese?

### ISSUE THREAD

**Issue by fzdwx** [charmbracelet/bubbletea#393]
When I use textinput, an error (could not decode rune) occurs when entering Chinese，i found that it is probably the following place:
![image](https://user-images.githubusercontent.com/65269574/183875980-79f17fa6-b1a7-4e3d-9fed-4e1e819d885b.png)

Then I wrote a test code:
```go
func main() {
	test(os.Stdin)

	reader, _ := cancelreader.NewReader(os.Stdin)
	test(reader)
}

func test(reader io.Reader) {
	var buf [256]byte
	n, err := reader.Read(buf[:])
	if err != nil {
		fmt.Println(err)
	}

	r, _ := utf8.DecodeRune(buf[:n])
	fmt.Println("decode error ? ", r == utf8.RuneError)
	fmt.Printf("%s \n", string(r))
	fmt.Println(buf[:n])

	fmt.Println("=============")
}
```
When I type `好`, `os.stdin` returns the result correctly, but `cancelreader` does not

output
```code
$ go run .
好
decode error ?  false
好
[229 165 189 13 10]
=============
decode error ?  true
�
[186 195]
=============
```

**Comment by fzdwx** [comment]
go version go1.19 windows/amd64

**Comment by fzdwx** [comment]
Check out this issue https://github.com/golang/go/issues/54389#issuecomment-1212934902

**Comment by fzdwx** [comment]
I'll deal with it briefly first, maybe there is a better way?

https://github.com/fzdwx/bubbletea/commit/c084728dd5ff6d468685ea26641c6b593cdbd5c5#diff-b671b685e8fe79217ba8d94722b5f7eb907906fa540c4104a30f104f7b2dd0d8R501

**Comment by knz** [comment]
As explained in the upstream issue, it looks like this input is not utf-8.

**Comment by fzdwx** [comment]
yes, windows is `GB18030`

https://github.com/golang/go/issues/54389#issuecomment-1212934902

**Comment by meowgorithm** [comment]
Yeah, so it likely does not make sense to support non UTF-8 encodings, unfortunately.

**Comment by meowgorithm** [comment]
Actually, I wonder if https://github.com/charmbracelet/bubbletea/pull/343 would fix this. @fzdwx would you mind checking?

**Comment by fzdwx** [comment]
Yes, it fixed! @meowgorithm 

---
But I have a second question:

On Windows run tea.program use ` windows.GetConsoleMode`  -> 992
but default mode is `503`, so after running, the input direction key will be recognized as `[[A`

![image](https://user-images.githubusercontent.com/65269574/185522147-1080a68d-4735-49a9-8751-72451ee25586.png)

code: 
```go
package main

import (
	"fmt"
	"golang.org/x/sys/windows"
	"unicode/utf16"
)

var fileShareValidFlags uint32 = 0x00000007

func main() {
	var originalMode uint32

	handle, _ := windows.CreateFile(
		&(utf16.Encode([]rune("CONIN$\x00"))[0]), windows.GENERIC_READ|windows.GENERIC_WRITE,
		fileShareValidFlags, nil, windows.OPEN_EXISTING, windows.FILE_FLAG_OVERLAPPED, 0)

	_ = windows.GetConsoleMode(handle, &originalMode)

    // 503
	fmt.Println(originalMode)

	// problematic mode
	//windows.SetConsoleMode(handle, 992)
}
```

**Comment by meowgorithm** [comment]
@fzdwx Would you mind opening a separate issue for this since it's a bit of a separate topic? That way it won't get lost.

**Comment by meowgorithm** [comment]
@fzdwx This is now fixed in `master` and will be available in the next release.

**Comment by fzdwx** [comment]
Thanks, it works! 🎉
