### ISSUE TITLE
Using tea.Printf before tea.Quit

### ISSUE THREAD

**Issue by asdine** [charmbracelet/bubbletea#413]
it is quite difficult to use the `tea.Printf` and `tea.Println` functions right before `tea.Quit`.
When using it with `tea.Batch` and `tea.Quit` for example, there is a race between `tea.Printf` and `tea.Quit`.

Example:

```go
// in this example, we are dealing with a list of tasks,
// display the latest state then start the next task.

  case foo:
     m.current++
     // if there is still work to do
     return m, tea.Batch( // this works fine
       tea.Println(m.tasks[m.current-1].View()),
       m.tasks[m.current].Update(),
     )
     // ...
     // Last element of the list, print it and leave the program
     return m, tea.Batch( // this doesn't work, race between Println and Quit
       tea.Println(m.tasks[m.current-1].View()),
       tea.Quit,
     )
```

By design `tea.Batch` doesn't provide any ordering guarantees, however its use with `tea.Printf` and `tea.Quit` makes it difficult to display *all* messages before quitting the program.

(If I understand correctly, the tea.Print* [example](https://github.com/charmbracelet/bubbletea/blob/master/examples/package-manager/main.go) has the same issue, although it misses the first entry in the list (it's more visible if you deactivate the randomness of the packages function))

I tried with `tea.Sequentially` but it returns the first non-nil message, this ignores the `tea.Quit` message.

Ideally I would like to use `tea.Printf`, then once it's rendered, use `tea.Quit`. Example:

```go
  return m, tea.QuitAfter(tea.Printf("...."))

```

What is the proper way of using `tea.Printf` and then `tea.Quit`?

**Comment by meowgorithm** [comment]
This is a really good catch and, unfortunately, there's no solution yet. It may actually be possible to adjust `tea.Sequentially` internally so that it works commands that return non-nil messages. If that doesn't work I'll return with some other possible solutions.

**Comment by meowgorithm** [comment]
Alright, so it still needs to be vetted, but I added a [`sequence`](https://github.com/charmbracelet/bubbletea/tree/sequence) branch which introduces the `Sequence` command that allows you to run commands in order.

```go
cmd := tea.Sequence(tea.Println("A"), tea.Println("B"), tea.Println("C"), tea.Quit)
```

[Full example here](https://github.com/charmbracelet/bubbletea/blob/45a7afc8956f29770b6a06b41f8400c0e02dd6d8/examples/sequence/main.go). Would love hear what you think.

**Comment by asdine** [comment]
It works great! I managed to run `tea.Println` and `tea.Quit ` sequentially with no issue.
