### ISSUE TITLE
Stop renderer from painting over prompt

### ISSUE THREAD

**Issue by hinshun** [charmbracelet/bubbletea#414]
I'm trying to write a tea program that activates from a shell key bind. I would like it painting below the prompt like how "ctrl+T" fzf works. It's currently painting over the prompt. Even better if I can paint the first line of the model inline with the prompt.

Here's a demo where I run it directly, which works fine. But when activating the zsh key bind, the renderer paints over the prompt. And I also lose my ansi colors.

[snipedit.webm](https://user-images.githubusercontent.com/6493975/186267627-6563892e-4cda-4981-bd3b-23222fee4a7a.webm)

Source: https://github.com/hinshun/snipedit

**Comment by hinshun** [comment]
I fixed my ansi colors not showing on stderr via: https://github.com/charmbracelet/bubbletea/discussions/386#discussioncomment-3304202

**Comment by muesli** [comment]
I believe this is intentional behavior when executing a key bind in your zsh prompt. You could probably reposition the cursor manually, but the prompt (re-)draw methods might not like that. Closing as I don't think we can do anything here.

**Comment by hinshun** [comment]
Fzf's "ctrl+T" key bind in zsh works as my desired behavior and it seems to be the better default for any bubbletea program activated via key binding. Surely there could be something we could look at?

**Comment by muesli** [comment]
I'm open for any ideas. Figuring out how exactly fzf behaves in this regard would be a good first step, I guess.
