### ISSUE TITLE
Display issue when line content is greater than terminal width

### ISSUE THREAD

**Issue by hbollon** [charmbracelet/bubbletea#43]
Hi! 
Thanks for this awesome library but I experience an issue with my tui when the displayed content is longer than the terminal width.
Here a gif:
![issue_bubbletea](https://user-images.githubusercontent.com/27230141/104303542-7e0f7000-54ca-11eb-8d7a-211910344e87.gif)

Maybe it's from my side, here my View() code for the main menu:
```go
s = fmt.Sprintf("\n🦄 Welcome to %s, the (soon) most powerful and versatile %s bot!\n\n", keyword("IGopher"), keyword("Instagram"))

for i, choice := range m.homeScreen.choices {
	cursor := " "
	if m.homeScreen.cursor == i {
		cursor = cursorColor(">")
	}
	s += fmt.Sprintf("%s %s\n", cursor, choice)
}

s += subtle("\nup/down: select") + dot + subtle("enter: choose") + dot + subtle("ctrl+c: quit")
break
```

Btw all of my tui code is available here : [tui.go](https://github.com/hbollon/IGopher/blob/master/cmd/igopher/tui/tui.go)
If you have any ideas

**Comment by meowgorithm** [comment]
Hi! Bubble Tea checks the window size for you, but it's your responsibility to wrap or trim your lines. Listen for [`tea.WindowSizeMsg`](https://pkg.go.dev/github.com/charmbracelet/bubbletea#WindowSizeMsg) in `Update` and then trim or wrap your strings accordingly.  I recommend the [reflow](https://github.com/muesli/reflow) package for doing word wrapping as it works nicely with ANSI-formatted strings. Note that `WindowSizeMsg` is sent before the first render and then again every resize.

So in update:

```go
switch msg := msg.(type) {
case tea.WindowSizeMsg:
    model.width = msg.width
    model.height = msg.height // height is available too
}
```

And then in your view:

```go
import "github.com/muesli/reflow/wordwrap"

func (m model) View() string {
    return wordwrap.String(m.bigLongString, m.width)
}

```

**Comment by meowgorithm** [comment]
Also, I personally like to set a max width when word wrapping for readability, so I'd probably do something like:

```go
const maxWidth = 80

func (m model) View() string {
    return wordwrap.String(m.bigLongString, min(m.width, maxWidth))
}

func min(a, b int) int {
    if a < b {
        return a
    }
}
```

**Comment by hbollon** [comment]
Nice ! I didn't know about WindowSizeMsg, it's really cool!
And I will follow your advice for the maximum width :+1: 
Thanks mate!

**Comment by Dentrax** [comment]
Hey @meowgorithm, I have an exact same issue but for terminal `height` instead. I fill a `bytes.Buffer` that exceeds my terminal height and have some overlapping, overdrawing issues. Should I file a new issue for this? `Display issue when line content is greater than terminal height`
