### ISSUE TITLE
Unknown CSI inputs result in garbage key events

### ISSUE THREAD

**Issue by knz** [charmbracelet/bubbletea#466]
When a terminal CSI sequence is not recognized by bubbletea, it is not completely ignored; instead, bubbletea will match the initial escape byte and the character immediately afterwards as a single key with the alt modifier, then interpret the rest as regular key inputs. For example, ESC [ 1003 h  gets parsed as alt+1, then 0, then 0, then 3, then h.

Since the CSI sequences all have a regular structure, they could be parsed and ignored as a single unit.

(The definition is strict: a CSI sequence starts with `ESC [` and terminates with a byte value in the range 0x40 to 0x7E.)

**Comment by muesli** [comment]
Could you elaborate how such a sequence would be triggered?

**Comment by knz** [comment]
> Could you elaborate how such a sequence would be triggered?

For example until #396 gets merged, if you press Shift+Home in xterm you get:
- 1 key message for Alt+1
- 1 separate message for a single `l` character
- 1 separate message for `2`
- 1 final message for `H`.
