### ISSUE TITLE
Consider adding working GIFs for each example

### ISSUE THREAD

**Issue by Dentrax** [charmbracelet/bubbletea#468]
It would be great to have working GIFs for each example in the [./example](https://github.com/charmbracelet/bubbletea/tree/master/examples) folder. 😍

**Comment by maaslalani** [comment]
Hey, thanks so much for opening this ticket.

We are working on this and will have some recorded GIFs for all of the examples very soon.

However, I will close this ticket as it is a duplicate of https://github.com/charmbracelet/bubbletea/issues/351

**Comment by Dentrax** [comment]
🚀 Cool! Thanks.
