### ISSUE TITLE
Altscreen enter and exit messages

### ISSUE THREAD

**Issue by meowgorithm** [charmbracelet/bubbletea#49]
Right now the only way to enter and exit the altscreen (full window mode) is via `Program.EnterAltScreen()` and `Program.ExitAltScreen()`. This means that, without employing hacks, one can only enter and exit when starting and quitting programs. It probably makes sense to have library-level commands, similar to `tea.Quit`, for entering and exiting the altscreen to give Bubble Tea programs the opportunity to jump in and out of the altscreen in-program.

**Comment by kiyonlin** [comment]
This is a good idea. So we should provide 2 Msg `tea.EnterAltScreen` and `tea.ExitAltScreen`. User can trigger them in Update if they want to change the alt screen mode.

I think I can submit a PR if you haven't done this.

**Comment by meowgorithm** [comment]
That would be awesome, @kiyonlin. Please do feel free to submit a PR. I’d probably call them `tea.EnterAltScreenMsg` and `tea.ExitAltScreenMsg` for naming consistency (like `tea.KeyMsg` and `tea.WindowSizeMsg`).

**Comment by meowgorithm** [comment]
Actually, @kiyonlin; there’s a branch I should merge before you do this. I’ll do that in a few minutes and let you know when it’s in.

**Comment by kiyonlin** [comment]
Dw, I will do it tomorrow (9 hours later) 😃

**Comment by meowgorithm** [comment]
@kiyonlin Alright, go for it. There are some small changes in how the alt screen is set in #61 (just merged) but it shouldn't change your implementation.

**Comment by meowgorithm** [comment]
Oh, just one more thought: realizing we'll also need two commands in addition to messages which I'd probably call `tea.EnterAltScreen` and `tea.ExitAltScreen`.

**Comment by meowgorithm** [comment]
This has been merged and was released in v0.13.0.
