### ISSUE TITLE
docs: show examples of using the `key.WithHelp()` for keybinds

### ISSUE THREAD

**Issue by bashbunni** [charmbracelet/bubbletea#492]
none of our Bubble Tea examples show how to use the key.WithHelp() in the description of the help menu. Would be good to show for people who are using keybinds in their programs so the help menu isn't being manually generated.

**Comment by titanventura** [comment]
would like to take this up

**Comment by titanventura** [comment]
So, should i pick an example from the existing list and add code to it or create a new example to demonstrate this ?

**Comment by bashbunni** [comment]
You can definitely use an existing example (our list examples are often referenced) and copy it to a new example specifically for key.WithHelp

**Comment by titanventura** [comment]
Sure Bunni !

**Comment by titanventura** [comment]
Hey bunni ! Seems like the demo of `key.WithHelp()` is already available at `examples/help/main.go`. Can I create a new example that uses `key.WithHelp` in it ?

**Comment by bashbunni** [comment]
Hey @titanventura 

ah geee, it looks like they implemented it when I brought it up internally. I'll have to close this issue since it seems it has already been implemented. If you're looking for more good first issues, I'd recommend taking a look at [Soft Serve](https://github.com/charmbracelet/soft-serve/issues) or [Skate](https://github.com/charmbracelet/skate/issues) if you're struggling to find some for Bubble Tea.

Sorry about the confusion!
