### ISSUE TITLE
Non-Interactive in Windows Shells

### ISSUE THREAD

**Issue by Splode** [charmbracelet/bubbletea#5]
## Issue

Running the example in the README in Windows is not working as expected (see screenshot).

![Screenshot 2020-10-12 185102](https://user-images.githubusercontent.com/13758438/95802926-014adb00-0cbc-11eb-9488-e2aa184ccc39.png)

## Expected Behavior

- Build and run the example in the README.
- Update the cursor position in the view via the _up, down, j, k,_ keys, etc.
- Exit cleanly by pressing _Ctrl+c_ or _q_

## Actual Behavior

- Cursor position does not update on key press, using any of _up, down, j, k, enter, space_
- Pressing _q_ does not quit the application.
- Pressing Ctrl+c exits with an error code.

## Environment

Windows 10 19041.508
Go 1.15.2
Terminal applications tested:
- cmd
- Powershell
- Windows terminal with Powershell and cmd
- Cmder with cmd, Powershell, cygwin 

## Other Notes

I was able to get the same example running as expected using WSL Ubuntu 20.04 with Windows Terminal.

The project looks exciting and I'm interested in diving deeper. Please let me know if there's any additional info I can provide.

**Comment by meowgorithm** [comment]
Thanks for trying out Bubble Tea! We don't technically support Windows yet, but do plan to do so in the near-ish future. Barring any unforseen issues, this should just be a matter of [enabling raw mode](https://docs.microsoft.com/en-us/windows/console/high-level-console-modes).

PRs are welcome, but otherwise we'll update this thread with progress.

**Comment by Splode** [comment]
@meowgorithm fair enough. Thank you for the swift reply!

**Comment by meowgorithm** [comment]
Hi! Just a note that Bubble Tea now supports Windows.

**Comment by Splode** [comment]
> Hi! Just a note that Bubble Tea now supports Windows.

Whoa, that was fast. Cheers!

**Comment by meowgorithm** [comment]
Thinking about it some more, some keybindings may not be functional (possibly the arrow keys, for example) as Windows likely sends different sequences for various keys compared to Unix systems. I’ll check on that and register anything I find missing.

Cheers!

**Comment by meowgorithm** [comment]
Alrighty! Bubble Tea now supports arrow keys on Windows.
