### ISSUE TITLE
p.Run undefined (type *tea.Program has no field or method Run)

### ISSUE THREAD

**Issue by acezx-programer** [charmbracelet/bubbletea#522]
when i run bubble tea(for example [this](https://github.com/charmbracelet/bubbletea/tree/master/examples/chat) )
gave me this error
client.go:20:17: p.Run undefined (type *tea.Program has no field or method Run)
so I'm new to go and i don't understand it very well, can somebody help me?

**Comment by muesli** [comment]
`p.Run` is a newly introduced method that will become available in the next stable release. Please use the docs & examples matching the version of Bubble Tea you have installed, likely the last stable release:

https://github.com/charmbracelet/bubbletea/tree/v0.22.1

**Comment by ayubkrakenflex** [comment]
@acezx-programer  I had the same issue, as in the comment above, using v0.22.1

change 

```
func main() {
	p := tea.NewProgram(model{})
	if _, err := p.Run(); err != nil {
		fmt.Printf("Alas, there's been an error: %v", err)
		os.Exit(1)
	}
}
```
to

```
func main() {
	p := tea.NewProgram(initialModel())
	if err := p.Start(); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}
```
