### ISSUE TITLE
Bubble tea hangs when the cancel reader is unable to cancel the read

### ISSUE THREAD

**Issue by aschey** [charmbracelet/bubbletea#524]
Issue is present as of https://github.com/charmbracelet/bubbletea/commit/b9bd01b79a8b73065396f286f207c919485cb317. To reproduce, hit `ctrl+c` when running a Bubble Tea program in Windows Terminal.

https://github.com/charmbracelet/bubbletea/commit/6477a53545c7da1ffd3ed9c6df68d87eb554d86d changed the behavior so that Bubble Tea waits for the read loop to complete when the shutdown sequence is initiated. However, if the cancel reader is unable to cancel the read, then the read loop never returns and the program is unable to shutdown. Not really sure what can be done here other than just continue with shutdown if `cancelReader.Cancel()` returns `false`.

**Comment by muesli** [comment]
Do you have an example that makes this easily reproducible?

**Comment by muesli** [comment]
Could you check if #525 resolves this regression?

**Comment by muesli** [comment]
Thanks for reporting it <3
