### ISSUE TITLE
update go.mod of examples folders

### ISSUE THREAD

**Issue by summer-boythink** [charmbracelet/bubbletea#546]
When I copied an example and used it, I found that it had an error telling me that it had no method for `Run()`. I looked up the source code and found that I needed to use `Start()` instead of `Run()`. In my opinion, this is because `go.mod` is too old. I think the examples 
 need to update go.mod.

The code I used:https://github.com/charmbracelet/bubbletea/blob/master/examples/table/main.go#L180

**Comment by muesli** [comment]
The examples reference the tea library in the parent folder. `Run` is a new method in `master`, which hasn't been part of a stable release yet. Either switch to `bubbletea@master` or check out the docs of the last stable release.

**Comment by summer-boythink** [comment]
@muesli Well, thank you for your reply
