### ISSUE TITLE
tea: long ticks delay message 

### ISSUE THREAD

**Issue by knz** [charmbracelet/bubbletea#547]
I've found a bug thanks to the new example @muesli is introducing in  #532: a long tick message delays messages after it.

This is because this code is incorrect:
```go
    go p.Send(cmd())
```

it should be instead:
```go
go func() { p.Send(cmd()) }()
```

i.e. the call to `cmd()` should be done asynchronously, not just the call to Send.

**Comment by knz** [comment]
i'll send a pr

**Comment by muesli** [comment]
Thanks @knz, good find!
