### ISSUE TITLE
p.Run undefined (type *tea.Program has no field or method Run)

### ISSUE THREAD

**Issue by kevsturman** [charmbracelet/bubbletea#552]
Not sure if this is a bug or a documentation issue. 

Following the tutorial in the readme and I get this error 
```
p.Run undefined (type *tea.Program has no field or method Run)
```

I can get the tutorial example working if I change `p.Run` to `p.Start`. Is this a document change or a code change issue?

**Comment by muesli** [comment]
`Run` is a new method in `master` and it sounds like you're using the last stable version of tea. I suggest either bumping your tea dependency to `master` or switching to the documentation of the last release.
