### ISSUE TITLE
Windows Terminal stops respond on input after bubbletea app quit

### ISSUE THREAD

**Issue by magodo** [charmbracelet/bubbletea#563]
## Step to reproduce

With following simple code built into `foo.exe`:

```go
func main() {
	fmt.Printf(`> `)
	var input string
	fmt.Scanf("%s", &input)
	fmt.Printf("Read: %s\n", input)
}
```

Then run the app defined in https://github.com/charmbracelet/bubbletea/tree/a7067fbfa2ed2cb89b3eeff1bde9ccd1870765aa/examples/simple. After this quits and `foo.exe` runs again, when the terminal is waiting for user's input, the cursor doesn't respond, and also any input doesn't show:

![input](https://user-images.githubusercontent.com/7970698/196861908-acf98830-bb5a-4b5a-86b8-4f21ebf50db6.gif)

**Comment by muesli** [comment]
Might be related to #408.
