### ISSUE TITLE
README Documentation on master is ahead of latest release for Run()

### ISSUE THREAD

**Issue by taigrr** [charmbracelet/bubbletea#564]
Reading through the README, Commit #6b77c8f changes the usage of Run() vs Start() vs StartReturningModel() 12 days ago, but the most recent release was Aug 19. Therefore, the instructions provided can't be followed without using a go replace directive or a workspace file.

I would request this issue stays open for those new to bubbletea as a helpful pointer until a new tagged release becomes available.

Pointer: until a release after v0.22.1 becomes available, use `StartReturningModel()` in place of `Run()`

**Comment by enrichman** [comment]
Thanks, I've encountered the same issue.

**Comment by taigrr** [comment]
New code paths are available after point release! Closing.
