### ISSUE TITLE
feat: add support for `BatchMsg` in `sequenceMsg`

### ISSUE THREAD

**Issue by stoffeastrom** [charmbracelet/bubbletea#582]
#415 added new `Sequence` command. This command should run the passed commands in order. However it doesn't take `Batch` command into account.

**Comment by stoffeastrom** [comment]
@meowgorithm what do you think about this? Something that could be considered?

**Comment by meowgorithm** [comment]
@stoffeastrom Yep, absolutely. Thanks for raising this issue?

**Comment by stoffeastrom** [comment]
@meowgorithm Great, Did a PR but not sure if I need to do anymore except waiting for you guys to 👀 on it :D
