### ISSUE TITLE
Error in tutorials: tea.NewProgram(model{}).Run undefined (type *tea.Program has no field or method Run)

### ISSUE THREAD

**Issue by darrenparkinson** [charmbracelet/bubbletea#591]
Running through the tutorials in the READMEs [here](https://github.com/charmbracelet/bubbletea/blob/master/README.md) and [here](https://github.com/charmbracelet/bubbletea/tree/master/tutorials/commands/), both of which produce the error: `tea.NewProgram(model{}).Run undefined (type *tea.Program has no field or method Run)`.

I can get them to run by changing main from:

```go
if _, err := tea.NewProgram(model{}).Run(); err != nil {
	fmt.Printf("Uh oh, there was an error: %v\n", err)
	os.Exit(1)
}
```

to this:

```go
if err := tea.NewProgram(model{}).Start(); err != nil {
	fmt.Printf("Uh oh, there was an error: %v\n", err)
	os.Exit(1)
}
```

Is that correct?
Many thanks.

**Comment by muesli** [comment]
`Run` is part of the just released (like, 5 minutes ago) v0.23.0 release. Please update to that version. Alternatively, yes, you can keep using `Start` with older tea releases.
