### ISSUE TITLE
Can I read from channels and Update the model?

### ISSUE THREAD

**Issue by rew1nter** [charmbracelet/bubbletea#596]
I went through the tutorials, bubbles, and a few examples but couldn't figure this out. Is this possible to listen to a channel and update the model?

**Comment by deicon** [comment]
Sure. You might want to look at how glow uses a channel to load files. 

https://github.com/charmbracelet/glow/blob/4dd3ba1d3c2b47a68b3ee4a7f30f97b0e5b18c78/ui/ui.go

`func findNextLocalFile(m model) tea.Cmd {
	return func() tea.Msg {
		res, ok := <-m.localFileFinder

		if ok {
			// Okay now find the next one
			return foundLocalFileMsg(res)
		}
		// We're done
		if debug {
			log.Println("local file search finished")
		}
		return localFileSearchFinished{}
	}
}`

**Comment by rew1nter** [comment]
Can't wrap my head around it, unfortunately. Could you please show how this piece of code would work [in the realtime example](https://github.com/charmbracelet/bubbletea/blob/master/examples/realtime/main.go) to transfer strings over channel?

**Comment by deicon** [comment]
Not sure what the exact problem is here. The sample does exactly what you where asking for. I didn't know this one but the more complex one in glow. But still they both do the same thing. 

In Init(), we send out two commands. One for each side of the channel. 
```
listenForActivity(m.sub), // generate activity
waitForActivity(m.sub),   // wait for activity
```

Those two methods return a cmd each. Each command basically is an action, which once it finishes delivers a message. Message can transport data. 
Once a Message is received, it is passed into the *Update* Method of the model, where the Model can react on the message and literally update its state aka model. 

So in this example, the listenForActivity(...) function is actually simulation any asynch call by simply waiting before sending a message onto the channel. It does this in an endless loop. So once the message is pushed into the channel its going to sleep again before another message is sent. This command is kind of misusing the ELM Architecture, as the command never actually returns a message. All it does is, that it constantly pushes out messages onto a channel. 

````
func listenForActivity(sub chan struct{}) tea.Cmd {
	return func() tea.Msg {
		for {
			time.Sleep(time.Millisecond * time.Duration(rand.Int63n(900)+100))
			sub <- struct{}{}
		}
	}
}

````
That covers the sending part of the channel. 

The other side of the channel simply receives data from the channel and returns it as a message which will end up in one of the next calls to the models Update method. 

````

func listenForActivity(sub chan struct{}) tea.Cmd {
	return func() tea.Msg {
		for {
			time.Sleep(time.Millisecond * time.Duration(rand.Int63n(900)+100))
			sub <- struct{}{}
		}
	}
}
````


All thats missing is the action on the message within the Update method. Whenever a message of the *responseMsg* type is received, all it does is to count the message and return the same command again by call *waitForActivity) again
```
case responseMsg:
		m.responses++                    // record external activity
		return m, waitForActivity(m.sub) // wait for next event
```


I am not sure if this is of any help.

**Comment by rew1nter** [comment]
Great explanation! That definitely helped me understand it better.

Heres what I'm trying to do. Lets say the channel is of type `string` and `listenForActivity()` func looks like this:
```golang

func listenForActivity(sub chan string) tea.Cmd {
	return func() tea.Msg {
		for {
			time.Sleep(time.Millisecond * time.Duration(rand.Int63n(900)+100))
			sub <- "this is str"
		}
	}
}

```
where the `waitForActivity()` func is listening to the channel for `string`. Now in that case how'd I access and print the data that  `waitForActivity()` function receives?

**Comment by rew1nter** [comment]
```golang
case responseMsg:
		m.responses++                    // record external activity
		return m, waitForActivity(m.sub) // wait for next event
```
Here its just incrementing the an int in the struct upon a message. Whereas Im trying to read what actually came out of `waitForActivity` function. Hope I've been able to explain what I'm trying to do.

**Comment by deicon** [comment]
Almost there.
instead of sending a string, you send a Message containing the string (data). Thats how Messages work here actually. 
````
type MessageStruct struct {
     data string
}

func listenForActivity(sub chan string) tea.Cmd {
	return func() tea.Msg {
		for {
			time.Sleep(time.Millisecond * time.Duration(rand.Int63n(900)+100))
			sub <- MessageStruct{
                                         data: "thestring"
                                     }
		}
	}
}
````

So the Cmd is returning a message using a typed struct containing your data. 
All the channel reading cmd does is to take the received message and pass it on as a bubbletea message. All what happens here is that the Message received from the channel is passed on to Update() message.


```
// A command that waits for the activity on a channel.
func waitForActivity(sub chan struct{}) tea.Cmd {
	return func() tea.Msg {
		return responseMsg(<-sub)
	}
}
```

With the Update Message the message is received and we can easily get to the data

```
case MessageStruct:
                fmt.Printf("Message contains %s", msg.data)
                // restarting the reading by calling the waitForActivity again,
		return m, waitForActivity(m.sub) // wait for next event
```

Sos thats all there is to it. If this all does not make sense, please consider taking a step back and start with simple examples, not using channels. Just to get the basic concepts of Command, Messages and how the Update View Cycle actually works.

**Comment by rew1nter** [comment]
Perfect! This is exactly what I was trying to do. Thanks for the help.
