### ISSUE TITLE
Can I set a custom size for the progress bar and increment it for progress?

### ISSUE THREAD

**Issue by rew1nter** [charmbracelet/bubbletea#604]
I'm trying to do something like [this](https://github.com/schollz/progressbar#basic-usage). Is this or something similar possible?

**Comment by fzdwx** [comment]
I have done something similar, you can refer to https://github.com/fzdwx/infinite/blob/main/_examples/progress/main.go

**Comment by rew1nter** [comment]
I figured out this is easily doable using the ViewAs() func. You just have to divide 1 by your total progress count and the result is what you increment for each progress.
