### ISSUE TITLE
`eventLoop` `sequenceMsg` should check `cmd` is not `nil`

### ISSUE THREAD

**Issue by nderjung** [charmbracelet/bubbletea#639]
Supplying a cmd which is `nil` (which may be mixed in a sequence of `cmds`) will result in a nil pointer exception when the [`eventLoop` iterates over the list of `msg`](https://github.com/charmbracelet/bubbletea/blob/master/tea.go#L313).

This issue tracks a simple `if cmd != nil` to be added before invoking `cmd()`.

**Comment by meowgorithm** [comment]
Thanks so much for catching this one! Merging your PR shortly.
