### ISSUE TITLE
Can't figure out how to show error in dedicated field in credit-card-example

### ISSUE THREAD

**Issue by gattiroberto1985** [charmbracelet/bubbletea#654]
Hello,

i see that in the `credit-card-form` example [here](https://github.com/charmbracelet/bubbletea/blob/master/examples/credit-card-form/main.go) that an `error` is stored in the model and an `errMsg` message is handled in the `Update` function. But i cannot make the error visible in the UI, nothing appears if i input a wrong character, neither if i print the error explicitly in the `View` function (if the error is not `nil`). It seems that the `errMsg` is never activated. 

I can't find any documentation or example about this, is there something wrong in the example?
Thanks in advance!

**Comment by hopefulTex** [comment]
The validation functions are called by the text models whenever one receives the `Update(teaMsg)` call, all you have to do is pass it a message and the rest is taken care of.  As for the `errMsg` , that's going to have whatever errors are passed into your program model itself, while the text inputs do error handling in their own `Update()` methods.
The errors are stored in the individual textinputs, `m.inputs[n].Err` , and they're set to `nil` if there's no error.

**Comment by bashbunni** [comment]
Hey @hopefulTex,

This is an issue that's being [discussed](https://github.com/charmbracelet/bubbles/pull/185) upstream in Bubbles. It would make more sense to continue the discussions and apply improvements over there. Thank you for bringing this to our attention! We haven't forgotten about this issue
