### ISSUE TITLE
border render dislocation in table example 

### ISSUE THREAD

**Issue by axeprpr** [charmbracelet/bubbletea#670]
windows btw
![image](https://user-images.githubusercontent.com/8937600/219831910-f3e2dc5a-3baa-4d05-a060-568207259e7e.png)

**Comment by 404name** [comment]
I encountered the same problem on the windows system. Considering that the table symbols are not adapted to windows?

With other bubbletea based [projects](https://github.com/knipferrc/fm) like this
![image](https://user-images.githubusercontent.com/56631419/226174001-73de37eb-7b34-4431-8570-d0dcc4008fa6.png)

**Comment by 404name** [comment]
oh..I think we forgot to set the encoding`chcp 65001` 
![image](https://user-images.githubusercontent.com/56631419/226174534-7bf6c889-8235-4bce-a762-7cf05edb0c9d.png)

![image](https://user-images.githubusercontent.com/56631419/226174482-f8783352-ef09-4e01-a276-75214ff226ff.png)

**Comment by bashbunni** [comment]
Hey @axeprpr what encoding are you using? I think this is related to the Lip Gloss border rendering issue we've seen when the encoding is not utf-8. I've got an open PR to answer this in our FAQ for Lip Gloss (our styling library)
https://github.com/charmbracelet/lipgloss/pull/189/files

**Comment by bashbunni** [comment]
@axeprpr and @404name were you able to fix this based on the info in our [Lip Gloss FAQ](https://github.com/charmbracelet/lipgloss#faq)? This is likely an issue based on your encoding locale. Please let me know if you still need help with this one, otherwise I will close it :)

**Comment by bashbunni** [comment]
Going to close this issue as answered. If someone has this same issue and it needs to be reopened, just let us know! :)

**Comment by axeprpr** [comment]
![image](https://github.com/charmbracelet/bubbletea/assets/8937600/95703a16-0ce4-4467-bc59-a888a2d6062b)

**Comment by axeprpr** [comment]
> Going to close this issue as answered. If someone has this same issue and it needs to be reopened, just let us know! :)
Sorry, I haven't logged in for a long time
