### ISSUE TITLE
Question: How print output from TODO

### ISSUE THREAD

**Issue by abtris** [charmbracelet/bubbletea#7]
I try it example and it's great library, but I can't figure out how you think we can work with output. 

Example: 

I can just add print for selected output:

```go
for i := range m.selected {
  fmt.Printf("\n%s", m.choices[i])
}
```

I can put into update function to quit and get ugly output:

```
What should we buy at the market?

> [x] Buy carrots
  [ ] Buy celery
  [x] Buy kohlrabi

Press q to quit.

Buy kohlrabi
            Buy carrots%
```

Do I need extra view for that? Or is some simple way how get pass output via program interface to main function to continue for example with other program? I see example with Msg but look overcomplicated for just work with output from CLI.

**Comment by meowgorithm** [comment]
Hi! So if I understand correctly, you want to capture the output of a choice, exit Bubble Tea, and then do something with that value?

**Comment by abtris** [comment]
Yes, that is simple example of usage. 

From interface perspective I think if you have possibility to extend interface `func NewProgram(init Init, update Update, view View) *Program` to some way that you have access to model via instance of program to process Model outside that will be useful for people using tool for example as input to process. 

```
What I can show download?
- [ ] nodejs 
- [ ] ruby
- [ ] go

press q to quit/continue
```
and as output will be:

```
You select nodejs and I'm downloading latest nodejs from ...
``` 

in func main can be for example: 

```
func main() {
    p := tea.NewProgram(initialize, update, view)
    if err := p.Start(); err != nil {
        fmt.Printf("Alas, there's been an error: %v", err)
        os.Exit(1)
    } else {
      m := p.GetModel() // whatever make sense
      makeDownload(m.url)
    }
    
}
``` 

or 

```
func main() {
    p, model := tea.NewProgram(initialize, update, view)
    if err := p.Start(); err != nil {
        fmt.Printf("Alas, there's been an error: %v", err)
        os.Exit(1)
    } else {     
      makeDownload(model.url)
    }
    
}
```

**Comment by meowgorithm** [comment]
That's a good idea. Since `Program.Start()` blocks we could potentially do something like:

```go
func main() {
    finalModel, err := tea.NewProgram(initialize, update, view).Start()
    if err != nil {
        fmt.Printf("Oh no!: %v\n", err)
        os.Exit(1)
    }

    m, ok := finalModel.(myModel)
    if ok {
        doSomething(model.url)
    }
}
```

Because the Bubble Tea runtime only knows the type as `tea.Model` you'd need to assert the model to whatever type you're actually using for the model (same as you'd do in the update function).

Depending on what the rest of your program looks like you could also just perform I/O in a command, which is typically how you’d do I/O in Bubble Tea (quick writeup [here](https://github.com/charmbracelet/bubbletea/tree/master/tutorials/commands) incase you haven’t seen it).

**Comment by meowgorithm** [comment]
After thinking about this some more, I think it makes the most sense to send final results back with a channel. [Here's an example](https://github.com/charmbracelet/bubbletea/blob/master/examples/result/main.go).
