### ISSUE TITLE
Accidentally dropped support for Solaris and Illumos?

### ISSUE THREAD

**Issue by twpayne** [charmbracelet/bubbletea#737]
**Describe the bug**

Prior to 35c31f21, bubbletea supported `GOOS=solaris` and `GOOS=illumos`.

35c31f21 bumped the version of [github.com/containerd/console](https://github.com/containerd/console) from v1.0.3 to the unreleased v1.0.4-0.20230313162750-1ae8d489ac81. This version of containerd/console includes https://github.com/containerd/console/commit/fa15abf58f2a4dcfbac2767caf17f57c3e029006, which drops support for Solaris and Illumos.

Is there any reason to drop support for Solaris and Illumos?

**To Reproduce**

```console
$ git clone https://github.com/charmbracelet/bubbletea.git
...
$ cd bubbletea
$ git checkout v0.24.0
...
$ GOOS=solaris GOARCH=amd64 go build .
# github.com/containerd/console
/Users/twp/pkg/mod/github.com/containerd/console@v1.0.4-0.20230313162750-1ae8d489ac81/console.go:83:12: undefined: checkConsole
/Users/twp/pkg/mod/github.com/containerd/console@v1.0.4-0.20230313162750-1ae8d489ac81/console.go:86:9: undefined: newMaster
```

**Source Code**
n/a

**Expected behavior**
bubbletea builds with `GOOS=solaris` and `GOOS=illumos`.

**Screenshots**
n/a

**Additional context**
n/a

**Comment by twpayne** [comment]
I opened https://github.com/containerd/console/pull/76 to restore Solaris support to containerd/console.

**Comment by muesli** [comment]
That was indeed unintentional. I bumped to that particular console revision for unrelated Windows fixes. Thanks for opening a PR over there, @twpayne!

**Comment by twpayne** [comment]
So, there's not been much interest from the containerd/console developers in restoring Solaris support. See https://github.com/containerd/console/issues/75 and https://github.com/containerd/console/pull/76.

As I want to support these OSes, I am currently [blacklisting charmbracelet repos](https://github.com/twpayne/chezmoi/blob/006230cc05fc1fe017c942758ee92aee3058d9c5/go.mod#L135-L138) that require the versions of containerd/console that drop Solaris and Illumos support. I also have a user request to run on AIX (https://github.com/twpayne/chezmoi/issues/2787), and if containerd/console is dropping support for Solaris and Illumos then it is extremely unlikely that they would want to support AIX.

Where do we go from here?

As the current versions I could continue to blacklist charmbracelet repos. I don't need the new charmbracelet functionality yet, but this creates extra maintenance effort for me as I have to blacklist each new version and is a poor long term strategy as at some point I will want to use some feature or bug fix that is only available in a more recent charmbracelet repo.

I would be happy to co-maintain a friendly fork of containerd/console that supports a full range of OSes. As I argue in https://github.com/containerd/console/issues/75#issuecomment-1567605232, I believe that the underlying APIs are stable and so maintaining such a repo would not be a significant burden. Given that charmbracelet is focused on console-based tools, to me it makes more sense to fork containerd/console to charmbracelet/console rather than twpayne/console.

Thoughts?

**Comment by muesli** [comment]
I agree, a friendly fork is probably the easiest way forward here. We actually require only very little functionality from containerd/console, which could also eventually be extracted.

**Comment by twpayne** [comment]
OK. If you want to fork containerd/console to charmbracelet/console then I'll open a PR to restore Solaris support and optionally strip out the unused functionality.

**Comment by muesli** [comment]
@twpayne There we go: https://github.com/charmbracelet/console

**Comment by bashbunni** [comment]
Next step: switch the dependency in Bubble Tea + other Charm apps that use console.

**Comment by twpayne** [comment]
Closing in favor of https://github.com/twpayne/chezmoi/pull/3060.
