### ISSUE TITLE
Style distortion under Win11 termina

### ISSUE THREAD

**Issue by debfig** [charmbracelet/bubbletea#786]
**Describe the bug**
Style distortion under Win11 termina

**Screenshots**
![](http://chanlie.space3v.work/20230723164841.png)

**Comment by meowgorithm** [comment]
Hi! This has to do with your locale (i.e. `zh_CN.UTF-8`). The easiest solve for this would be to set `RUNEWIDTH_EASTASIAN=1` in your environment, however there are other thugs you can do as well. See: https://github.com/charmbracelet/lipgloss/issues/40 for details.

(Dup of https://github.com/charmbracelet/lipgloss/issues/40)

**Comment by meowgorithm** [comment]
Thinking about this some more. Even though this pertains to Lip Gloss, and is not really a bug, I wonder if it makes sense to set/restore`RUNEWIDTH_EASTASIAN` on program start/shutdown to mintigate this issue.  Not totally understanding the implications yet, _think_ it’ll generally be harmless based on how runewidth is used with TUIs.

**Comment by debfig** [comment]
> Thinking about this some more. Even though this pertains to Lip Gloss, and is not really a bug, I wonder if it makes sense to set/restore on program start/shutdown to mintigate this issue. Not totally understanding the implications yet, _think_ it’ll generally be harmless based on how runewidth is used with TUIs.`RUNEWIDTH_EASTASIAN`

Thank you for your answer, which was very helpful to me. I am very sorry that I should not have thought this was a mistake
