### ISSUE TITLE
missing mouse example gif

### ISSUE THREAD

**Issue by Caixetadev** [charmbracelet/bubbletea#816]
## [Readme](https://github.com/charmbracelet/bubbletea/blob/master/examples/mouse/README.md)

![image](https://github.com/charmbracelet/bubbletea/assets/87894998/41328635-e9aa-4ab4-9622-7bf7839746bb)

## [Raw](https://raw.githubusercontent.com/charmbracelet/bubbletea/master/examples/mouse/README.md)
![image](https://github.com/charmbracelet/bubbletea/assets/87894998/a22a8aaa-4bc7-4f16-ba0d-b451cede539d)

**Comment by meowgorithm** [comment]
@maaslalani mouse isn't something we can script with VHS yet is it?

**Comment by maaslalani** [comment]
I believe the Pipe example does have a GIF https://github.com/charmbracelet/bubbletea/tree/master/examples/pipe

I've removed the README so that it is not missing an image which is consistent with the other examples that do not have GIFs currently.

**Comment by meowgorithm** [comment]
Sounds good. Thank you!

**Comment by meowgorithm** [comment]
Closing this for now as I think it's fine as-is. If people feel differently we can discuss and potentially re-open. Happy New Year!
