### ISSUE TITLE
Bubble tea doesn't render colors on tmux over ssh

### ISSUE THREAD

**Issue by idvorkin** [charmbracelet/bubbletea#825]
**Describe the bug**
When using bubble tea on tmux over ssh, there are no colors being rendered. It works fine on ssh without tmux.

**Setup**
Please complete the following information along with version numbers, if applicable.
 - OS: Linux
 - Shell: Zsh
 - Terminal Emulator: iTerm and Blink
 - Terminal Multiplexer: Tmux over ssh and over mosh 

**To Reproduce**
1. Go to examples/alt-screen (I suspect issues always reproduce here)
4. See the red text not rendered in color.

**Comment by meowgorithm** [comment]
Hi! I'm not able to reproduce this, both with and without tmux running locally in addition to remotely. To make sure I'm understanding correctly, can you confirm you're doing the following:

2. SSH'ing into a Linux server
3. Running `tmux`on the remote server
4. Running the `examples/alt-screen`

Additionally, what is the `$TERM` value in your environment in `tmux` on the server?

**Comment by idvorkin** [comment]
That's correct: 

On SSH
<img width="1203" alt="image" src="https://github.com/charmbracelet/bubbletea/assets/280981/a70055eb-a6c1-4f19-9394-fd5b1f419e37">

On SSH+TMUX
![image](https://github.com/charmbracelet/bubbletea/assets/280981/e34917ea-5b28-40b6-bf82-01aafdadd488)

SSH+TMUX in

**Comment by idvorkin** [comment]
@meowgorithm  - Happy to run any diagnostics you'd like. true color works fine in other apps (not based on bubble tea)

**Comment by yanllllk** [comment]
edit your ~/.tmux.conf
add 
`set -g default-terminal "screen-256color"`
save file. 
restart your tmux.

**Comment by idvorkin** [comment]
Oh that fixed it! Hooray. Now I wonder if that messed up something else, atleast True Color still works!

Can we treat the xterm-256color the same as screen-256color for others?

**Comment by meowgorithm** [comment]
Hi! I'd file an issue upstream in [`termenv`](https://github.com/muesli/termenv) where this detection takes place. Also note that Bubble Tea actually doesn't manage color, style and layout; would file future issues around this in [Lip Gloss](https://github.com/charmbracelet/lipgloss).

**Comment by idvorkin** [comment]
Sigh, if you screen-256color, that breaks italics. BUT, turns out setting COLORTERM is what iTerm does, and that gives truecolor support.

    COLORTERM=truecolor
