### ISSUE TITLE
Last line truncated from the output when sending the `tea.Quit` command

### ISSUE THREAD

**Issue by praagyajoshi** [charmbracelet/bubbletea#827]
First off, thanks for this awesome library! I had a ton of fun creating a small CLI app with it.

**Describe the bug**
When a `tea.Quit` message is triggered from the `Update()` method, the last line defined in the `View()` method gets truncated.

**Setup**
Please complete the following information along with version numbers, if applicable.
 - OS: macOS
 - Shell: tried on both `zsh` & `fish`
 - Terminal Emulator: tried on both iTerm and Terminal.app
 - Terminal Multiplexer: none

**To Reproduce**
I've created a minimal reproduction here: https://gist.github.com/praagyajoshi/1244e79a44e308e4ebd43a844d159d5c
This is a simple program which updates the model with a string message on any keypress.

You can comment line 30 and uncomment line 32 to see the bug in action.

**Expected behavior**
The last line of the string returned by `Output()`  should always be displayed.

**Screenshots**

_Initial run_
![CleanShot 2023-09-23 at 12 22 27@2x](https://github.com/charmbracelet/bubbletea/assets/2060518/f67728e2-d0aa-4994-b0c1-733c0b7fb5ea)

_On any key press_
![CleanShot 2023-09-23 at 12 22 46@2x](https://github.com/charmbracelet/bubbletea/assets/2060518/ba4ee9b6-324a-4d77-979c-362a58933f62)

**Comment by meowgorithm** [comment]
Hi! So what's happening is that your prompt is overwriting the final line printed by Bubble Tea. There are some pros and cons to changing this behavior, which we've discussed here and there (see #304). For now, I'd simply add a final newline to the end of of your views on quit (most of the inline examples work this way).

If you have more thoughts on this mind following up in #304?

(Dup of #304)

**Comment by praagyajoshi** [comment]
Got it, thanks for the super quick response @meowgorithm.

> For now, I'd simply add a final newline to the end of of your views on quit (most of the inline examples work this way).

Yep, agree. That's what I'm doing currently.

> If you have more thoughts on this mind following up in [#304](https://github.com/charmbracelet/bubbletea/issues/304)?

Will do! I can close this one.
