### ISSUE TITLE
Docs outdated

### ISSUE THREAD

**Issue by MB175** [charmbracelet/bubbletea#856]
https://github.com/charmbracelet/bubbletea/blob/5536bca34e218a1e17a55e5ba36c22fab5784f44/tutorials/basics/main.go#L81C33-L81C33

Some `ProgramOption` are needed

**Comment by meowgorithm** [comment]
Hi! What kind of options are you expecting in this tutorial? By default, no `ProgramOption`s are needed in Bubble Tea and the tutorial here is intended to be a simple, minimal example.

**Comment by meowgorithm** [comment]
Hey again! We're closing this for now, but please do chime in if you have more details and we'll reopen if it makes sense. We do love good documentation!
