### ISSUE TITLE
Need examples on lipgloss integration

### ISSUE THREAD

**Issue by flowchartsman** [charmbracelet/bubbletea#88]
[lipgloss](https://github.com/charmbracelet/lipgloss) looks great, but its  example seems to indicate dynamic, updateable, switchable widget-based content, which is not the case at all. The [example](https://camo.githubusercontent.com/5ed63e6b61ddcea9575c0b0eefd373c8f085f4594e323fe60c39ce3bbcc27d81/68747470733a2f2f73747566662e636861726d2e73682f6c6970676c6f73732f6c6970676c6f73732d6578616d706c652e706e67) is in fact completely static, and none of the bubbletea examples have any kind of layout or focus switching, so it's unclear if a dynamic, switchable version of the lipgloss example is even possible, or how the two projects might integrate together.

**Comment by meowgorithm** [comment]
We'll plan on adding some examples, but what you're describing actually isn't as complicated as it appears. Lip Gloss just outputs strings, so you'd simply use Lip Gloss styles and functions in your Bubble Tea views (which also output strings). You could easily put the Lip Gloss example into a Bubble Tea view, and replace various parts of the content with data from your model.

You might want to have a look at [fm](https://github.com/knipferrc/fm), which is using Lip Gloss in its views (and is in heavy development at the moment). In particular, check out the [feature/panes](https://github.com/knipferrc/fm/tree/feature/panes) branch which is using Lip Gloss to render two interactive views side-by-side.

**Comment by bashbunni** [comment]
Filmed a quick explanation of this - will edit + publish on YouTube and add PR with the link in the README

**Comment by muesli** [comment]
We also have a bunch more examples using lipgloss in the repo by now - I think we can close this issue.

**Comment by rahji** [comment]
To be honest, I still don't think any of the examples illustrate how simple it is. A simple example is going from this:

```go
func (m model) View() string {
        text := fmt.Sprintf(
                "Enter stuff:\n\n%s\n\n%s",
                m.textarea.View(),
                "(ctrl+c to quit)",
        ) + "\n"
        return text
}
```

to this:

```go
func (m model) View() string {
        text := fmt.Sprintf(
                "Enter stuff:\n\n%s\n\n%s",
                m.textarea.View(),
                "(ctrl+c to quit)",
        ) + "\n"
        style := lipgloss.NewStyle().
                SetString(text).
                Width(50).
                Foreground(lipgloss.Color("63"))
        return style.Render()
}
```
