### ISSUE TITLE
autocomplete example not valid anymore

### ISSUE THREAD

**Issue by erdemkosk** [charmbracelet/bubbletea#882]
**Describe the bug**
When try to run this example there is no such a SetSuggestions and ti.ShowSuggestions = true values in textInput.

**Setup**
Please complete the following information along with version numbers, if applicable.
 - OS [macOS]
 - Shell [zsh,]
 - Terminal Emulator [iterm]

**To Reproduce**
1. Go to 'https://github.com/charmbracelet/bubbletea/blob/master/examples/autocomplete/main.go'
2. Try to run in local

**Comment by erdemkosk** [comment]
m.textInput.SetSuggestions undefined (type textinput.Model has no field or method SetSuggestions)compiler[MissingFieldOrMethod](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#MissingFieldOrMethod)

m.textInput.SetSuggestions undefined (type textinput.Model has no field or method SetSuggestions)compiler[MissingFieldOrMethod](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#MissingFieldOrMethod)

**Comment by naglis** [comment]
The autocomplete functionality is not yet included in a `bubbles` release. Therefore, `bubbles` dependency in the `examples` module [is pinned to a commit](https://github.com/charmbracelet/bubbletea/blob/e671b840f205aa9fbc2fba9903290a1205390760/examples/go.mod#L6) that includes autocomplete functionality. Please check the version of [`bubbles`](https://github.com/charmbracelet/bubbles) you are using (e.g. in case you are using [`replace` directive](https://go.dev/ref/mod#go-mod-file-replace) to use a local copy of `bubbles` that is older than https://github.com/charmbracelet/bubbles/commit/eda891258c0223c437133e401b431975627d9104).

**Comment by meowgorithm** [comment]
Hi! So if I'm understanding things correctly we just need to do a release on Bubbles, correct? If that's indeed the case that's easy enough and we'd be happy to do so.

**Comment by naglis** [comment]
@meowgorithm I could not reproduce the OP issue, to me the autocomplete example works OK locally (the `bubbles` dependency in `examples` module [was bumped](https://github.com/charmbracelet/bubbles) to commit that includes the autocomplete functionality, so a new `bubbles` release should not be needed just for that).

From the error message it looks like an old version of `bubbles` is being used, so I suspect there might be some misconfiguration on OP's end.

**Comment by meowgorithm** [comment]
Thanks, @naglis! In any case, we just did a proper bubbles release and this should sort things out (@erdemkosk, let us know if not).
