### ISSUE TITLE
bubbletea does not render special characters properly

### ISSUE THREAD

**Issue by codedotspirit** [charmbracelet/bubbletea#907]
**Describe the bug**
When using, for example, German "Umlaute" `(ä, ü, ö)`, bubbletea does not render the characters at all. Another German-specific character, `ß`, renders as `á` instead. This does not seem to be a problem with the font, as I can use the letters when writing out commands.

**Setup**
Please complete the following information along with version numbers, if applicable.
 - OS: Windows
 - Shell: Windows Terminal/cmd

**To Reproduce**
1. Create a bubbletea application with a textinput
2. Try to type any of the letters into the textinput
4. See the characters not being typed/rendered

**Source Code**
The [textinput code example](https://github.com/charmbracelet/bubbletea/blob/master/examples/textinput/main.go) can be used to replicate this behaviour.

**Expected behavior**
The special characters should render, however, they do not.

**Screenshots**
Here is an example of what happens when typing in the `ß` character:
![image](https://github.com/charmbracelet/bubbletea/assets/66965600/ea7e45c4-6457-452b-8431-49f012c416f8)
To confirm, here you can see how my terminal renders the characters with the same font & settings:
![image](https://github.com/charmbracelet/bubbletea/assets/66965600/6f1ac0d9-f521-4fd2-b61a-148a6dd36a98)

**Comment by meowgorithm** [comment]
Okay cool, this seems to be an issue on Windows in particular (and possibly a regression). What's your exact locale, i.e. `de_DE.UTF-8`. I'm wondering if this has to do with the locale not being UTF-8.

There’s a duplicate issue at https://github.com/charmbracelet/bubbles/issues/460, however I think this repo is the appropriate place for this.

**Comment by meowgorithm** [comment]
Also, just to be thorough, what typeface are you using?

**Comment by meowgorithm** [comment]
Okey-dokey, this is now fixed on `master` via #878 and will be available in the next release. Cheers!

**Comment by meowgorithm** [comment]
All the credit here belongs to @aymanbagabas and @erikgeiser 🙂

If you don't mind let's close this out.

**Comment by codedotspirit** [comment]
Much love to you two then! Thanks again, marking this as closed.
