### ISSUE TITLE
`[ctrl+enter]` Support

### ISSUE THREAD

**Issue by NiloCK** [charmbracelet/bubbletea#927]
I'd like to respond to user input of `ctrl+enter` differently than `enter`. This is reasonably common now for various text inputs - eg, with `enter` doing a `\r\n`, but `ctrl-enter` triggering a submit or similar.

**Describe the solution you'd like**
[key.go](https://github.com/charmbracelet/bubbletea/blob/master/key.go) could provide `ctrl+enter` as a `KeyType`?

**Comment by meowgorithm** [comment]
Hi! Unfortunately, <kbd>ctrl+enter</kbd> isn't something historically supported by terminals. https://github.com/charmbracelet/bubbletea/issues/869 will add support for this in some capacity—though keep in mind that if you want to target all terminals everywhere <kbd>ctrl+enter</kbd> is not available as a keybinding.

**Comment by NiloCK** [comment]
Dang. I had guessed there was a good chance that there was some external limitation here - felt like an unusual omission.

Thanks.

**Comment by meowgorithm** [comment]
Yep. I'm going to close this as #869 will cover it but feel free to re-open if you feel it's still relevant.

**Comment by NiloCK** [comment]
Sounds good @meowgorithm, but a quick followup: does the same constraint apply to `shift+enter`?

**Comment by meowgorithm** [comment]
Unfortunately, yes.
