### ISSUE TITLE
Can't write japanese characters in inputfield

### ISSUE THREAD

**Issue by xyaman** [charmbracelet/bubbletea#976]
**Describe the bug**
Whenever I try to write japanese characters in textinput it's get rendered as "?". The inputfield value also contains "?". Every japanese character is rendered as "?"

**Setup**
Please complete the following information along with version numbers, if applicable.
 - Windows 11
 - Tested with CMD, Powershell, Git-Bash.
 - Tested with wezterm and Windows Terminal

**To Reproduce**
I have a very similar code with the tutorial, and rendering is being made by textinput. I'm using Microsoft IME.

**Screenshots**
![image](https://github.com/charmbracelet/bubbletea/assets/32078353/bb196131-5489-4f90-a5f6-d7b03fbeb5f1)
Should be 6 characters, but instead it shows "??????" (6*"?")

**Additional context**
Japanese characters rendering besides textinput is working fine.
![image](https://github.com/charmbracelet/bubbletea/assets/32078353/b24cd651-b616-4122-9eb2-4cfa37769784)

**Comment by Dmitrevicz** [comment]
Feels like same issue from here https://github.com/charmbracelet/bubbletea/issues/197#issuecomment-1240526302 (20 months old bug already). I saw people saying that it only occurs on Windows, but can't double-check it myself (I only have windows laptops rn).

**Comment by meowgorithm** [comment]
Hi! This should be fixed now in Bubble Tea v0.26.x. If not, please reopen the issue.
