### ISSUE TITLE
Allow WindowSizeMsg to be sent on sub-model Init

### ISSUE THREAD

**Issue by tylerolson** [charmbracelet/bubbletea#987]
When attempting to format content that is reliant on the width/height you must listen for `WindowSizeMsg` and store those values in the model:

```go
func (m model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	var cmd tea.Cmd
	switch msg := msg.(type) {
	case tea.WindowSizeMsg:
		m.width = msg.Width
  		m.height = msg.Height
        }
}
```

This presents a challenge when switching to a different model, as the `WindowSizeMsg` msg is never sent again.

This means that you must either use global variables to keep track of the width/height, or pass around width/height variables to all of your sub models:

```go
func newOtherModel(width int, height int) otherModel {
	return otherModel{
		width:    width,
		height:   height,
	}
}
```

**Describe the solution you'd like**
Either allow a way to manually request the current WindowSize at say, Init(), or maybe provide a way to update the current model without using a mainmodel-submodels type architecture.

Maybe this is a non-issue for most, just something I found :)

**Comment by meowgorithm** [comment]
Hi! So technically speaking you shouldn't use `Init` to initialize your model; its job is _just_ to return an initial command.

To pass the window width and height when switching to a new model you can simply set properties on the new model before returning it:

```go
func (m model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	switch msg := msg.(type) {
	case tea.WindowSizeMsg:
		m.width = msg.Width
  		m.height = msg.Height
		return m, nil

        case switchModelsMsg:
		newModel := NewModel()
		newModel{width: m.width, height: m.height} // pass along width/height
		return newModel, newModel.Init() // switch models
        }
}
```

**Comment by KevM** [comment]
In [bubbleo's navstack](https://github.com/KevM/bubbleo/blob/e8bf58588311a7d71c3c0335d46bd1abd867769b/navstack/model.go#L62) when pushing a new model on the stack I call Init and send the new model and Update with the window size msg for exactly the reason you mention. We need the model now in charge of the application to know what its size is.

**Comment by meowgorithm** [comment]
@KevM Cool, so sounds like we're basically saying the same thing, right?

**Comment by meowgorithm** [comment]
Reading this again, perhaps a `Cmd` for requesting the window size would indeed be useful.

**Comment by tylerolson** [comment]
@meowgorithm the main issue with that is I find having `width`/`height` properties in 4+ models gets really annoying. Especially when I'm moving from one model to another AND back (main menu and submenus), I had about 7 spots where im passing `width` `height` properties.

My initial thought was to just run `WindowSizeMsg` when any `Init()` is ran, however a request `Cmd` would probably be most useful in a vareity of circumstances

**Comment by KevM** [comment]
> @meowgorithm the main issue with that is I find having width/height properties in 4+ models gets really annoying. Especially when I'm moving from one model to another AND back (main menu and submenus), I had about 7 spots where im passing width height properties.

I ran into the same exact issue. My solution was to give my new "sub" model structs a optional field with [a pointer to a wrapper around the window state](https://github.com/KevM/bubbleo/blob/e8bf58588311a7d71c3c0335d46bd1abd867769b/window/model.go#L8). Maybe not the best solution but it worked for me. 🤷🏼
